---
title: "2026-06-01 Week 1 Lesson 1"
date: "2026-06-01"
categories: ["bordeaux", "af", "B1", "unite4"]
reference-location: document # margin, block, section, document
citation-location: document #margin
image: "https://images.unsplash.com/photo-1691145286899-db7bfd8e85f8?q=80&w=640"
--- 


# Le temps des loisir

C'est le temps pendant lequel on ne travaille pas. 
Profiter de la vie, de voyager, de sortir, prendre du plaisir
Sortir de la routine
S'acoorder du temps de famille, prendre du temps pour soi
Pratiquer des activités de loisirs / sportives (la randonnée à vélo)
Des activitiés culturelles

Ce sont des activités occasionnelles


l'œnologie , c'est une discipline qui consiste à sentir, regarder, goûter / déguster le vin.

listez les activités de loisirs: 

- le ski de randonée 
- aller au cinéma se faire une petite toile
- cuisine = passer du temps en cuisine
- faire du sport 
- chanter dans une chorale
- aller voir un spectacle (de danse, un concert, un opéra, une pièce de théâtre...)
- assister **à** un événement sportif
- jouer **d**'un instrument de musique
- jouer **à** un sport / pratiquer le foot / faire **de** + un sport 
- sortir le soir (aller en boîte = dans un ediscothèque, danser / écouter de la musique dans un bar)
- un marche
- s'entraîner dans une salle de sport
- faire du crochet / faire du tricot / faire de la couture / faire de la broderie
- la lecture
- collecter(=collectionner) des objets anciens = faire un collection
- faire de la méditation(méditer) et du yoga
- apprendre une langue étrangère
- faire du jardinage
- salon du bien-être (prendre soin de soi = s'occuper de soi = se faire du bien) 


# Texte - Les loisirs des Français

## Le texte et des activités

[Les loisirs des Français](https://www.podcastfrancaisfacile.com/texte/loisirs-des-francais.html)


## Développement

Répondez librement aux questions ci-dessous.

1. Comment occupez-vous votre temps?

Pour les loisirs, je prefére des activités gastronomies comme faire de cuisine et l'œnologie. Souvent, je faire aussi de la randonnée à pieds ou à velo. 

2. Y a-t-il des différences entre les loisirs en France et les loisirs dans votre pays?

À mon avis, il n'y a pas trops des différences s'agissant des loisirs en France et aux États Unis. Plusieurs des gens preférent passer le temps sur les écrans, ou sur des autres activités passives / solitaires. C'est la malheur de temps contemporains. 












