---
title: "2026-06-22 Week 4 Lesson 16"
date: "2026-06-22"
categories: ["bordeaux", "af", "B1", "unite6"]
reference-location: document # margin, block, section, document
citation-location: document #margin
image: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?q=80&w=640"
---


# Le précis

Les lexiques de parler de l'art



# Lexique

- une personne ouverte  
- ouvrir un espace / un horizon  
- [s'ouvrir]{.underline} **à** d'autres idées / la vie  
- des autres, à des époques 
- [ouvrir]{.underline} une fenêtre **sur** la culture / l'imaginaire  
- ouvrir son esprit / son cœur / son âme  

- avoir une ouverture d'esprit / un esprit ouvert
- développer son ouverture d'esprit  
- la compréhension des choses, adopter un regard différent
- se retourver à soi-même = prendre le temps d'être avec l'œuvre, être au contact avec l'œuvre
- les beaux-arts 
- un chef-d'œuvre (notes le "f" dans chef-d'œuvre n'est pas prononcé)


- Provoquer des émotions
- L'art provoque des émotions sur moi il y a des œuvres d'art qui stimulent ou encouragent à développer notre pensée, à voire autrement
- ça fait écho en moi.
- faire naître des sentiments positifs ou négatifs
- ça fait remonter des sentiments ([it brings back feelings]{.fst-italic})
- développer la créativité
- L'art, c'est une question de perception, d'appréciation, de ressenti, de percevoir/apprécier/ressentir des émotions
  - je percois / j'apprécie / je ressens
- [adhérer à]{.underline} un type de création
- ça touche mon cœur / mon âme / mon esprit
- ça me donne des émotions, ça me procure des émotions
- ça m'émeut ([émouvoir]{.underline .fst-italic} [= to move, to touch emotionally]{.fst-italic})
  - un tableau m'émeut
  - je suis ému(e) 
- mettre l'intention de l'artiste en valeur ([highlight the artist's intention]{.fst-italic})
- je peux vivre sans peinture mais je ne peux pas vivre sans musique.
  - sans + nom (pas d'article) 
- transmettre des émotions
- le spectacle vivant ([live performance]{.fst-italic})
- avoir un fond musical, créer une ambiance
- Hiérachiser (sans hiérarchie)

