---
title: "Le Nouveau Taxi 3 - Leçon 10"
date: "2025-10-8"
categories: ["Le Nouveau Taxi", "B1", "les pronoms complément" ]
reference-location: margin
citation-location: margin
---


## Grammaire - Les pronoms compléments: des verbes qui n'utilisent pas de COI

### à + qch - y

J'ai pensé à une idée.  
→ J'y ai pensé.

Il a réfléchi à cette proposition.  
→ Il y a a réfléchi.

### à + qn - les pronoms COI (me, te, lui, nous, vous, leur)

Je lui ai donné un livre.  
Il m'a offert un cadeau.  
Nous leur avons raconté cette histoire.  

### à + qn - les pronoms toniques (moi, toi, lui, elle, nous, vous, eux, elles)

Remember these verbs use pronoms toniques, not COI pronouns:  
- penser à  
- songer à  (to think about)
- avoir affaire à (to deal with)  
- faire attention à (to pay attention to)  
- être à qn (to belong to someone)

Je pense à elle.  
J'ai eu affaire à lui.  
Cette voiture est à moi. 

_Note the à [tonic] are always after these verbs._

### à + qn - verbes reflexifs, always use tonic

e.g.  
se fier à (to trust)  
s'habituer à (to get used to)  
s'intéresser à (to be interested in)  
se référer à (to refer to)  
s'opposer à (to oppose)  
s'adresser à (to address)  
... etc.  

Je m'intéresse beaucoup à lui.  
Adressez-vous à elle, s'il vous plaît.

_Note the à [tonic] are always after these verbs._

## Entraînez-vous

- Dites-moi, << Luca >>, c'est votre véritable nom?  
- Mais oui, ce nom je (1)_______ ai hérité de mes parents et j'(2)_______ tiens beaucoup. Pour rien au monde je ne (3)______ changerai!  
- Seriez-vous d'accord pour dire que votre succès, vous (4)______ devez en partie[^2a1] à votre imprésario Johnny Res qui a disparu tragiquement l'été dernier?  
- Oui, bien sûr, je (5)______ dois tout et je pense tous les jours à (6)______ . Ne plus (7)______ voir, ça, je ne m'(8)______ habitue pas!  
- Certains professionnels du spectacle n'ont pas été tendre avec vous, vous (9)______ en voulez?  
- Non, je ne m'intéresse pas à (10)______ et je (11)______ laisse le choix général, qu'elles soient bonnes ou mauvaises, je n'(12)______ fais pas attention.  

>
1. l'  
2. y (tenir à qch: to care about something)  
3. le (devoir qch à qn/qch: to owe something to someone/something)  
4. le  
5. lui  
6. lui  
7. le  
8. y (s'habituer à qch: to get used to something)
9. leur (en vouloir à qn: to be angry with someone)  
10. eux  
11. leur (laisser qch à qn)
12. y (here it refers to the fact, not the people)


[^2a1]: in part, partly


## Texte

### part 1 - Olivia Ruiz

Olivia Ruiz  
_Chanteuse francaise, née à Carcassonne le 1er janvier 1980._

Dès[^2a1] l'âge de 12 ans, Olivia Ruiz monte sur scène et dévelope des dons[^2a2] artistiques variés: elle prend des cours de danse, monte son propre groupe de rock, les Five, et chante en duo avec son père, Didier Blanc, lui-même musicien et chanteur. 

:::{.callout-tip}
#### monter
monter sur scène - to go on stage  
monter un groupe - to form a group  
monter une entreprise - to start a business  
monter une tente - to set up a tent  
monter une machine - to assemble a machine
:::


[^2a1]: dès = à partir de, depuis
[^2a2]: le don = le talent



Après avoir obtenu un BTS de communication, la jeune femme rejoint la saison 1 de la Star Academy, qui lui permet de se faire connaître. Ses deux albums, _J'aime pas l'amour_, sorti en 2003 et _la Femme chocolat_, en 2005, sont surprenants d'originalité. Lors des Victoires de la musique 2007, elle remporte la Victoire de l'Artiste interprète féminine de l'année et la Victoire du Spectacle musicale de l'année. 

:::{.callout-tip}
#### après avoir + [participe passé] / après être + [participe passé]
avoir participe passé - a passé composé at the start of a sentence is a common construct in French, similar to English. Note, when the auxiliary verb is être and the verb is NOT reflexive, the auxiliary verb can be omitted.

- Après avoir obtenu un diplôme, il a trouvé un emploi.  
- Après être rentré / Rentré chez lui, il s'est effondré dans le canapé (effondré = collapsed, canapé = sofa).  
- Après s'être parlé, ils se sont dit au revoir. 
:::

:::{.callout-tip}
#### se faire + [infinitif]
Note the difference between:  
- faire [infinitif] à qu (to do something to someone)  
- se faire [infinitif] à qn (to make something happen or done to oneself)  

Il s'est fait couper les cheveux. (He had his hair cut.)


:::







### part 2 - 












## Thème







