---
title: "Défi 4: Unité 2"
date: "2026-2-8"
categories: ["AF Nice", "B2", "Défi4", "Unit2" ]
reference-location: margin
citation-location: margin
number-sections: false
---

# Standard course

### INITIATIVES AGRICOLES AU MAGHREB

Le Maroc, l'Algérie et la Tunisie partagent le même climat, la même végétation et les mêmes problématiques: la sècheresse[^1a1] des sols et la diminution des terres cultivables. Autres points communs: une population rurale très importante et un potentiel agricole porté par des femmes, dans des exploitations à taille[^1a2] humaine. Ces initiatives locales nous montrent que, parfois, des solutions résident dans les problèmes.


[^1a1]: sècheresse = dryness, drought
[^1a2]: à taille humaine = human scale, taille = size

#### Focus Maroc

Avril 2019, le SIAM, le Salon international de l'agriculture au Maroc, présente pour la première fois un espace réservé à l'agriculture biologique. Parmi les exposants, Malika Mouilek, 2éme lauréate du prix Terre de Femmes Maroc 2019, défend à la fois l'agriculture biologique et le travail des femmes dans son village de Dour Laglalcha. Selon elle, l'agriculture intensive a fait diminuer les stocks d'eau et a dégradé la qualité du sol. Uniquement vendus sur les marchés locaux, les argrumes et produits maraîchers biologiques de ces femmes ne bénéficient pas de certi







