---
title: "Le Nouveau Taxi 3 - Leçon 11"
date: "2025-10-10"
categories: ["Le Nouveau Taxi", "B1", "les modalisateurs des adjectifs" ]
reference-location: margin
citation-location: margin
---


## Grammaire - Les modalisateurs

Les modalisateurs sont les mots et les procédés grammaticaux qui traduisent le jugement et les sentiments (certitudes, incertitudes, appréciations positives ou négatives, etc.) de celui qui parle par rapport à ce qu'il dit. Ces modalisateurs peuvent être notamment: 

### des adjectifs{.unnumbered} 
 _intéressant, excellent, épatant[^1a1], formidable, agréable, satisfaisant, génial, super, nul[^1a2], sûr, vraisemlable[^1a3]_, etc.  

>
Le choix des artistes retenus (selected) est **épatant**.  
On va dépasser les 90%, c'est globalement(generally) **satisfaisant**.

### des adverbes{.unnumbered} 
_sans doute, peut-être, certainement, plutôt, assez, super, trop, franchement[^1a4], évidemment, probablement, réellement[^1a5], vraiment, heureusement_, etc.


[^1a1]: amazing, fantastic  
[^1a2]: worthless, rubbish  
[^1a3]: likely, plausible
[^1a4]: frankly, honestly  
[^1a5]: actually, really

## Texte


### Léo à l'affiche du bac

Vous le saviez, vous, que la chanson française et **au programme du** bac 2009? Pas comme matière[^2a1] obligatoire **quand même**, ce serait trop beau, mais en << musique, option facultative[^2a2] toutes séries >>, comme c'est écrit dans le bulletin officiel n° 19 du 8 mai 2008, sur le site du ministère de l'Éducation nationale.
Des polyphonies de la Renaissance, et même...Jimi Hendrix, avaient eu droit à cet honneur il y a quelque années, mais pour la chanson d'ici et de maintenant, c'est la première fois. Et le choix de artistes retenus est, ma foi[^2a3], épatant; même si, pour la génération qui **planche dessus** depuis quelques mois, certains noms doivent être aussi inconnus que Christophe Maé chez les Indiens d'Amazonie.

À tout seigeur[^2a4] tout honneur, c'est Léo Ferré qui figure au sommet[^2a5] de la pile[^2a6] avec trois titres: Avec le temps, Requiem et Green, un poème de Verlaine. 

Bon, c'est vrai que les élèves ne **se précipitent** pas sur l'option, mais leur nombre est **suffisamment significatif pour qu**'une prof de musique, qui les fait plancher depuis la rentrée, puisse affirmer[^2a7] qu'il y a << une véritable[^2a8] demande >>.


:::{.callout-tip}
#### l'affiche
Le film est à l'affiche. (The film is showing, here l'affiche = the poster)  
Léo à l'affiche du bac. (Léo on the poster of the bac exam)
:::

:::{.callout-tip}
#### au programme de
on the syllabus of, in the program of  
- La sculpture est au programme de la seconde année. 
:::

:::{.callout-tip}
#### quand même
still, all the same, anyway  
- Cet espoir (hope) est toujours là qund même.  
- Le médecin lui a interdit de fumer, mais elle fume quand même.
:::

:::{.callout-tip}
#### avoir droit à qch
to have the right to sth, to be entitled to sth  
- Les habitants pékinois, à partir de l'âge de 65 ans, on droit à une carte qui leur permet de prendre gratuitement les autobus. 
- Les internautes qui ne payent pas n'auront pas droit au texte intégral de l'article. (full text of the article)
:::


:::{.callout-tip}
#### retenir
to select, to choose, to remember, to hold back...  
- Nous regrettons de ne pas pouvoir retenir votre proposition.
:::


:::{.callout-tip}
#### plancher...sur...
to work on, to study on, to spend time on...  
- Il a planché toute la nuit sur un problème de maths.
:::

:::{.callout-tip}
#### dessus, dessous, dedans
above, below, inside...  

dessus: sur qch  
- Tu vois cette montagne-là? Je voudrais monter dessus un jour. (dessus = sur la montagne)

dessous: sous qch  
- Le mendiant trouve une grosse pierre près de la rivière et cache son argent dessous. (dessous = sous la pierre)

dedans: dans qch  
- Le cambrioleur a réussi à ouvrir le coffre-fort, mais il n'y avait rien dedans. (dedans = dans le coffre-fort)
:::

:::{.callout-tip}
#### se précipiter
to rush, to hurry...  

précipiter = to throw oneself down, to hurl oneself...
:::

:::{.callout-tip}
#### suffisamment .... pour que + subjonctif
sufficiently ... so that...  
- Il est suffisamment intelligent pour réussir. (He is smart enough to succeed)

trop ... pour que + subjonctif
too ... so that...
- Il est trop fatigué pour travailler. (He is too tired to work)
:::


[^2a1]: = une discipline; subject
[^2a2]: optional, elective
[^2a3]: really, honestly, indeed; ma foi = my faith
[^2a4]: seigneur = lord; à tout seigneur tout honneur = give honour to whom honour is due
[^2a5]: sommet = summit, top
[^2a6]: pile = stack, pile, here it refers to a pile of songs
[^2a7]: affirmer = to state, to assert
[^2a8]: véritable = real, true, genuine


## Thème

1. Unviersity professors have about 3 months of vacation each year. 

>
Les professeurs on environ trois mois de vacances chaque année.

2. He speaks loudly so that everyone can hear him.

> 
Il parle suffissamment fort pour que tout le monde puisse l'entendre.  
Il parle assez fort pour se faire entrendre. 

3. They want to visit the summer palace so much that even the rain won't stop them.

>
Nous avons tellement envie de visiter le Palais d'Été que la pluie ne pourrait pas nous empêcher. 


4. His first job was to teach community seniors how to dance.

>
Son premier travail était d'apprendre à danser aux personnes âgées de la communauté.






