---
title: "Le Nouveau Taxi 3 - Leçon 2"
date: "2025-09-24"
categories: ["Le Nouveau Taxi", "B1"]
reference-location: margin
citation-location: margin
---

## Grammaire: L'expression de la cause

### parce que

1. Used to answer teh question "pourquoi"  

    > Pourquoi est-ce que tu es essoufflé?  
    > Parce que je suis monté les escaliers à pied.

2. Used in a clause

    > Elle rêvait de devenir danseuse. Mais elle a dû renoncer à son rêve parce qu’elle était handicapée.


### car

Often used in writing, more formal than "parce que". Always used in a clause after main clause.

> J'ai choisi la coloc car j'en avais marre[^1a1] de la solitude. 

[^1a1]: "en avoir marre de" = "to be fed up with"


### puisque
Used when the cause is obvious or already known. 既然.

> Puisq'il pleut, on pourrait rester à la maison.

### comme
Always used at the beginning of a sentence.

> Comme il pleuvait, Camille et moi, nous sommes restés à la maison.


### du fait que / vu que / étant donné que
Very formal, often used in writing, like in official / legal documents, etc. 鉴于， 由于。

> Du fait qu'il fait mauvais, le match sera reporté à la semaine prochaine.


### grâce à
Used to express a positive cause. 由于，多亏了。

> J’ai eu ce travail grâce à Olivier. 

### à cause de

Nous sommes arrivés en retard à cause des embouteillages[^1a2]. 

[^1a2]: traffic jams.

### à force de
Because of repeatedly doing something...

> À cause de crier, il s’est cassé la voix.

### faute de
Because of the lack of something...

> Faute de temps, il n’a pas fini le travail à temps.


### le gérondif

> Tu vois, en faisant un effort, tu as réussi.  
> En buvant du café, il a travaillé trés avant dans la nuit.




## Entraînez-vous

`comme`  
J'ai choisi de vivre en colocation: je ne connaissais personne à Paris. 

> Comme je ne connaissais personne à Paris, j’ai choisi de vivre en colocation. 


`à cause de`  
Ça posait un problème: nous avions tous des horaires différents.

> À cause des horaires différents que nous avions tous, ça posait un problème.


`le gérondif`  
Je partage mon appart avec deux amis, alors je suis devenu plus tolérant.

> En partageant mon appart avec deux amis, je suis devenu plus tolérant.


`car`  
On est restés seulement deux mois ensemble; on ne s’entendait pas du tout.

> On ne s’entendait pas du tout, car on est restés seulement deux mois ensemble.


`puisque`  
Les loyers ont beaucoup augmenté, ça me semblait être la meilleure solution.

> Puisque les loyers ont beaucoup augmenté, ça me semblait être la meilleure solution.

## Texte



## Thème - Translate into French



