---
title: "Lesson 13"
date: "2026-2-11"
categories: ["AF Nice", "B2", "Défi4", "Unit1" ]
reference-location: margin
citation-location: margin
number-sections: false
---

# Standard course

## LE TEXT

### QUELLES TRANSPORMATIONS LA VILLE INTELLIGENTE ENGENDRERA-T-ELLE?


Cette communication propose d'analyser les attraits[^1a1] des villes intelligentes pour les autorités publiques ainsi que[^1a2] les menaces qui en découlent[^1a3]. Ensuite, je terminerai en montrant les impacts que peut avoir l'exploitation des données numeriques sur les citoyens et la démocratie.

[^1a1]: attractiveness
[^1a2]: ainsi que = as well as
[^1a3]: découler = to result from

Intelligence technique, sysèmique, politique et culturelle... Il y a tellement de conceptions de *smart cities* que j'ai centré mon étude sur les villes qui collectent et traitent des données numériques pour optimiser leur fonctionnement. Dans ces villes, les autorités publiques travaillent notamment à fluidifier[^2a1] la mobilité urbaine, optimiser la consommation énergétique et améliorer la gestion de l'eau et des déchets. Malgré leurs enjeux[^2a2] communs, les objectifs visés[^2a3] par une ville comme Bankok sont assez éloignés[^2a4] de ceux d'Amsterdam. C'est pourquoi aucunne ville intelligente ne se ressemble vraiment. Néanmoins, elles partagent toutes un objectif ambitieux : vivre de mieux en mieux[^2a5] en ensemble. À Singapour, l'analyse du big data a permis, entre autres[^2a6], l'amélioration de la sécurité. 

[^2a1]: fluidifier = to make more fluid
[^2a2]: enjeux = stakes
[^2a3]: visé = aimed at
[^2a4]: far from, éloigner = to move away from
[^2a5]: vivre de mieux en mieux = to live better and better
[^2a6]: entre autres = among other things


Les mérites[^3a1] des villes intelligentes sont indéniables de sorte que[^3a2] certains élus[^3a3] les considèrent comme le remède[^3a4] à tous les maux. Par exemple, la proposition d'aménagement du quartier en friche de Quayside à Toronto (par Sidewalk Labs, filiale de Google) présente des innovations audacieuses: rues chauffants, Abribus capables de se déployer automatiquement en cas d'intempéries[^3a5], couloirs[^3a6] réservés aux différents modes de transport pouvant changer en fonction du trafic... Les avantages sont nombreux, au point qu'on[^3a7] pourrait oublier que dangers existent. L'usage abusif du big data conduit à une surveillance de masse des citoyens, si bien qu'on[^3a8] peut légitimement se demander: qui gourvernera la ville de demain? De ce fait, j'exposerai[^3a10] les menaces que représente l'exploitation des données numériques par une entreprise privée, car cette mainmise[^3a9] pourrait amener cette entreprise à devenir "propriétaire" de la ville.

[^3a1]: mérites = merits
[^3a2]: de sorte que = so that
[^3a3]: élus = elected officials
[^3a4]: remède = remedy
[^3a5]: intempéries = bad weather
[^3a6]: couloirs = lanes
[^3a7]: au point que = to the point that
[^3a8]: si bien que = so much so that
[^3a9]: mainmise = control
[^3a10]: exposer = to expose, to present


La ville est une société où cohabitent la vidéosurveillance, les réseaux sociaux et les objets connectés. Ces nouvelles formes de surveillance et de contrôle de la population sont sournoises[^4a1]. Tout est miniaturisé[^4a2] et caché: capteurs, caméras et objets connectés sont omniprésents et espionnent[^4a3] les habitants avec ou sans leur consentement. La collecte et l'analyse de toutes ces données (itinéraires, achats, propos sur les réseaux sociaux...) mènent[^4a4] à une société panoptique[^4a5] menaçant[^4a6] notre vie privée et la démocratie. D'où la nécessité d'instaurer des mesures pour que la "*smartification*" des villes se fasse dans l'intérêt de chacun et pas uniquement pour le profit de quelques géants du numérique. C'est la raison pour laquelle je présenterai plusieurs solutions pour la protection des données, telles[^4a7] les techniques d'anonymisation ou le développement de technologies protectrices de la vie privée. 


[^4a1]: sournois = sneaky, underhanded
[^4a2]: miniaturized, miniaturiser = to miniaturize
[^4a3]: espionner = to spy on
[^4a4]: mener à = to lead to
[^4a5]: a society where everyone is under constant surveillance, named after the Panopticon prison design where inmates could be watched at all times without knowing when they were being observed
[^4a6]: menacer = to threaten
[^4a7]: telles que = such as, telles = such as, note the agreement with the plural noun "mesures" (feminine plural)


Dans le cadre de cette communication, je questionnerai le discours binaire[^5a1] opposant "fascination technologique" et "peur de Big Brother". Comme le précise[^5a2] l'économiste Jean Haëntjens, deux visions de la ville du futur sont en train de se dessiner: "D'un côté, la cité politique, dirigée[^5a3] par un maire élu par des citoyens, qui se fixe[^5a4] des ambitions à long terme en visant un intérêt général; de l'autre, la ville-service numerisée, pilotée par les 'maîtres des algorithmes', et qui vise à repondre en temps réel aux demandes des usages." La démocratie n'est pas forcément[^5a5] condamnée, c'est aux citadins de choisir, puisqu'ils sont à la fois citoyens et usagers. 

[^5a1]: binaire = binary, opposant = opposing
[^5a2]: noted, préciser = to specify, to clarify, to point out
[^5a3]: dirigé = directed, dirigé par = led by
[^5a4]: se fixer = to set oneself, to set goals
[^5a5]: pas forcément = not necessarily

## Activité 3 : Grammaire

*Livre de l’élève p.26*  

### Étape 1 : Réflexion   

#### Dans les phrases ci-dessous, qu'est-ce que les termes en gras introduisent?  

- *Les avantages sont nombreux (cause)*, au point qu'on pourrait oublier que des dangers existent (conséquence).
  - Intensité

- Il y a tellement de conceptions de smart cities que j'ai centré mon étude sur les villes qui traitent les données.
  - Intensité 

Convaincre les lecteurs de son point de vue.

#### À deux, lisez ces phrases. Qu'introduisent les verbes en gras? Reformulez les phrases avec des verbes différents.

- L'analyse du big data a permis l'amélioration de la sécurité.  
  - → L’analyse du big data a aidé / a facilité / a favorisé / a provoqué / à rendre possible l’amélioration de la sécurité.  

- Les villes intelligentes engendreront des transformations.  
  - → Les villes intelligentes produiront / provoqueront / concevront / conduiront à / mèneront à / généreront des transformations.

- L'usage du big data conduit à une surveillance de masse.  
  - → L’usage du big data produit / a permis / donne naissance à / entraîne / mène à / a pour conséquence / a provoqué une surveillance de masse.

### Étape 2 : La règle 

**Pour exprimer la conséquence, on peut utiliser :**   

- Un connecteur : donc, ainsi, du coup (à l’oral), par conséquent, c’est pourquoi, de ce fait, d’où.
  - ⚠️ D’où est suivi d’un nom.

- Un verbe : amener, causer, créer, mener à, provoquer, entraîner, susciter, aboutir à, permettre, donner naissance à, rendre possible, être le résultat de, engendrer, conduire à, découler de.

- Une expression + phrase à l'indicatif : de manière que, de façon que, de sorte que, si bien que, c’est la raison pour laquelle.

**Pour exprimer une conséquence avec une notion d’intensité ou de quantité, on utilise :**  

- Tant de / tellement de + nom + que  
- Au point que / à tel point que + phrase  
- Verbe + tellement / tant + que + phrase


## Vocabulaire

- Avoir la mainmise (exp.) sur quelque chose.  (= have control over something)
- Élire (v.) quelqu’un  (= to elect someone)
- Un colloque (n.m)  (= a conference)
- Engendrer (v.) quelque chose :   (= to generate something)
  - → Donner naissance à quelqu’un (sens littéraire)  (= to give birth to someone)
  - → Donner naissance à quelque chose (usage)  (= to give birth to something, to generate something)
- Diriger (v.)   (= to lead, to direct)
- Contrôler (v.)   (= to control)
- Instaurer (v.)  (= to establish, to set up)
- Sournois.e (adj.)  (= sneaky, underhanded)
- Une intempérie (n.f)  (= bad weather)
- Une filiale (n.f)  (= a subsidiary, a branch)
- Emprisonner (v.)   (= to imprison)
- Un engouement (n.m)  (= enthusiasm, craze)



## Devoirs

:::{.callout-important}
#### Devoirs
Pour le jeudi 12 février  

- Revoir la leçon de grammaire sur l’expression de la conséquence.  
- Exercice 19 p.26 du livre de l’élève (livre blanc). 
  - Faire l’exercice suivant à l’écrit (5 causes / conséquences) :   
  - Observez l'affiche des Utopiales, le festival international de science-fiction à Nantes. Décrivez la Nantes du futur en expliquant les causes et les conséquences des changements urbains.

:::

>
**Nantes en 2050**
>
Nantes en 2050, c'est une ville de culture, de nature, d'intelligence, de beauté, et surtout des gens. La ville a transformé par réimaginer et rédessiner avec les intelligences et les écologiques. Les transformations sont tellement réussies que la ville consomme toutes les énergies des sources renouvables. De ce fait, l'air et les rivières là-bas sont toujours clairs et sains. De nombreux secteurs industriels ont cédé à les espaces vertes, au point que est possible les algoricultures urbaines en grande échelle. Ces concessions et le retour de la nature dans et autour de la ville n'ont diminué pas la population urbaine. Au contraire, l'amélioration de l'ambiance et de l'environnement ont mené bien plus des gens à la ville. C'est la raison pour laquelle Nante a surpassé Paris et ensuite devient la prémière ville en France.  








