---
title: "2026-06-11 Week 2 Lesson 9"
date: "2026-06-11"
categories: ["bordeaux", "af", "B1", "unite5"]
reference-location: document # margin, block, section, document
citation-location: document #margin
image: "https://images.unsplash.com/photo-1645156568844-13cc8b4b1cf7?q=80&w=640"
---

# Le Précis

Lexique de l'aménagement urbain  
La négation  
L'ecoute et la transcription d'un document audio


# Lexique

[Vocabulaire de l'aménagement urbain]{.fw-bolder}

- réaménager / réoganiser
- privilégier la pietonnisation (les rues piétonnes)
- Développer la végétalisation
- créer des espaces verts / une voie verte 
- Élargir les trottoirs (rendre plus large)
- s'éloigner = loin
- se rapprocher = près
- allonger = long
- raccourcir = court
- border = le bord
- planter des arbres
- augmenter les espaces (masc.) / des zones (fem.) obragé(e)s (faire de l'ombre)
- réduire les nuisances sonores (le bruit, un quartier bruyant), la pollution
- bâtir des logements écologiques (2iem groupe = -IR = -IS, -ISS (vous bâtissez, ils bâtissent))
- l'amélioration
- l'détérioration
- un évolution = évoluer
- les rues larges / étroites
- être coloré / des couleurs
- le / la maire de la ville
- la mairie = la municipalité
- nettoyer = ils nettoient
- mettre des fleurs = fleurir des espaces / des entrées
- un espace fleuri


:::{.column width="98%"}
- un permis = une permission (permettre de + initif)
- une autorisation (autoriser qqn à faire qqch)
- tacitement = sans dire un mot, sans parler
:::














