---
title: "Le Nouveau Taxi 3 - Leçon 5"
date: "2025-09-28"
categories: ["Le Nouveau Taxi", "B1" , "Passé Composé", "L'imparfait"]
reference-location: margin
citation-location: margin
---

## Grammaire - L'imparfait vs. Passé Composé


:::{.callout-warning}
#### Les temps du récit

Le **présent** indique une situation actuelle ou une action poncturelle qui a lieu au moment où l'on parle:  
- Cette Bordelaise de 21 ans étudie les relations internationales.

Le **passé composé** permet de raconter des événements qui ont eu lieu dans le passé, il indique des actions accomplies et assure la trame chronologique du récit:  
- J'ai trouvé assez facilement un travail à temps partiel dans une boîte italienne.

**L'imparfait** apporte des précisions sur le contexte (circonstances, situation, habitudes, répétitions):  
- L'expérience était très géniale.  
- Dès qu'ils apprenaient que j'étais française, ils essayaient de me montrer qu'ils savaient dir << bonjour >>, << Moulin-Rouge >> et << camembert >>. 
:::


## Texte - europass

**_Laure Badia, 21 ans, a quitté Bordeaux pendant un an pour étudier en Angleterre._**

<< Les Britanniques, dés qu'ils apprenaient que j'étais française, essayaient de me montrer qu'ils savaient dire bonjour, Moulin-Rouge et camembert ! >>

Laure Badia vient de passer une année scolaire[^2a1] inoubliable à Swansea, au pays de Galles, dans le cadre d'un séjour Erasmus.


:::{.callout-tip}
#### dès que
as soon as  
- Je vous appellerai dès que je serai sorti de l'avion.  
- Il s'est mis au travail dès son arrivée au village.  
- Il est interdit de fumer dès l'entrée du bâtiment.

Note _dès que_ often leads a clause that is one tense before the tense of the main clause.
:::


:::{.callout-tip}
#### dans le cadre de
as part of, within the framework of  
- Ils ont signé un accord dans le cadre de coopération.  
- Le demandeur d'emploi (job seeker) qui effectue des déplacements dans le cadre de sa recherche d'emploi, peut bénéficier d'aides financières. 

effectuer: to perform (a task), to carry out
:::


[^2a1]: a school/academic year



Quand elle est partie, le 19 septembre dernier, elle n'a pas eu si peur d'aller à l'étranger puisque, pour elle, un pays membre de l'Union européenne n'est pas un pays si inconnu. Cette Bordelaise de 21 ans, qui étudie les relations internationales en license[^2b1] de langues étrangères appliquées, en a retiré une expérience formidable et dit maintenant appartenir à la << famille Erasmus >>, ancrée[^2b2] dans l'Europe.


:::{.callout-tip}
#### avoir peur de faire qch/de qch
to be afraid of doing sth/of sth  
- Il a peur de sortir tout seul.  
- Il a peur de son père.

:::


:::{.callout-tip}
#### si + adj. ou adv.
so, such  
- Il court si vite !  
- Il a connu une histoire si étrange.  

si ... que:  ... so ... that  
- Il a été si fatiqué qu'il s'est couché très tôt.  
- Il a couru si vite que l'on n'a pas pu l'arrêter.

:::


:::{.callout-tip}
#### retirer
to take away, to withdraw, to get (a benefit)  

retirer un profit de qch - to get a profit  
retirer unn exéprience de qch - to gain an experience  
retirer un intérêt de qch - to gain an interest or benefit

- Elle a retiré une expérience formidable de son séjour en France.  
- Il a retiré un grand profit de cet investissement.

:::


:::{.callout-tip}
#### appartenir à
to belong to  
- J'habite ici depuis deux ans. La maison ne m'appartient pas, mais à une grande amie de mes parents.

:::


[^2b1]: bachelor's degree, major
[^2b2]: anchored, rooted. s'ancrer = s'installer


**_Une Européenne_**

Laure explique que tout est fait pour que les étudiants étrangers se sentent intégrés[^2c1]: << L'accueil et les rencontres sont très bien organisés par l'université et les associations. Les étudiants gallois sont en général très curieux et enthousiastes à l'idée de[^2c2] connaïtre de nouvelles personnes. Je pense avoir été considérée[^2c3] avant tout[^2c4] comme une étudiante. >>  


::::{.callout-tip}
#### tout est fait pour que + subjunctif
everything is done so that...  
- Tout est fait pour qu'il soit satisfait.  
- Tout est fait pour que tout le monde comprenne.

:::


:::{.callout-tip}
#### se sentir + adj.
to feel + adj.  
- Te sens-tu capable de faire ce travail?  
- Ses trois filles se sentent toutes bien appréciés de leurs collègues.  他的三个女儿都觉得同事们很欣赏她们。

:::


[^2c1]: s'intégrer dans = to integrate oneself into
[^2c2]: à l'idée de = at the idea of
[^2c3]: considerer ... comme = to consider ... as
[^2c4]: avant tout = above all, first and foremost


Les Gallois restent  cependant[^2d1] très patriotiques. Il ne faut pas confondre << Welsh >> et << English >> quand on leur parle, conseille la jeune femme. Et même si[^2d2] l'Europe est considerée comme[^2d3] une chance, ils sont toujours hostile à[^2d4] l'adoption de la monnaie unique.
Selon elle, le sentiment d'appartenance à l'Europe se développe au cours du séjour: << Ce n'est pas quelque chose qu'il est possible d'apprendre à l'école ou en regardant des reportages. Il faut le vivre.
En résidant à l'étranger, on se rend compte que même si on a des langues et des habitudes différentes de nos colocataires ou de nos amis, on a finalement la même culture et beaucoup de points communs >>, assure-t-elle.


:::{.callout-tip}
#### au cours de
during, in the course of  
- Au cours de la réunion, le président a pris un discours.
- Au cours de ces années, il a beaucoup vielli.

:::


:::{.callout-tip}
#### il est + adj. + de + inf.
it is + adj. + to do sth   
- Il est possible d'étudier à l'étranger.  
- Il est important d'apprendre une langue étrangère.

:::


:::{.callout-tip}
#### se rendre compte que / de qch
to realize that / sth  
- Il s'est rendu compte qu'il ne l'aimait plus.  
- Il s'est rendu compte qu'il avait tort. (he realized he was wrong)  
- Elle s'est rendu compte de son erreur. 

:::


:::{.callout-tip}
#### assurer à qn que
to assure sb that...  
- Je lui ai assuré que tu n'habitais plus là-bas.  

être assuré de qch - to be sure of sth  
- Je suis assuré de son amitié.

:::


[^2d1]: however, nevertheless
[^2d2]: même si = even if, even though
[^2d3]: to be considered as
[^2d4]: être hostile à = hostile to / against


**_Une grande chance_**

L'étudiante bordelaise rentrera en France le 25 juin prochain, avec maintenant des amis résidant[^2e1] un peu partout en Europe et dans le monde et des connaissances sur leur pays et leurs habitudes.

<< L'ouverture[^2e2] des pays envers l'Union européenne est une grande chance. C'est une expérience unique de pouvoir dévouvrir un autre pays d'aussi près[^2e3] et de rencontrer des étudiants de nationalités si différentes. >>

:::{.callout-tip}
#### envers
towards  
- Son attitude envers cet homme est plustôt positive.  
- Il a montré son hostilité envers ce mouvement.  

envers et contre tous - against all odds  
- Elle voulait le marier envers et contre tous.

à l'envers - opposite, upside down  
- Elle a interprété toute ma parole à l'envers.  
- Maladroite (clumsy), elle a mis à l'envers ce portrait sur le mur. 

:::


[^2e1]: des amis résidant... = des amis qui résident...
[^2e2]: l'ouverture = openness, opening up
[^2e3]: d'aussi près = so closely, up close


## Thème


1. She drives a new car, but the car doesn't belong to her. 

`appartenir à qu`, `être à qn`

> Elle dispose d'une nouvelle voiture qui, cependant, ne lui appartient pas.  
> Elle est au volant d'une voiture toute neuve, mais elle ne lui appartient pas.  
> Elle conduit une voiture neuve qui, pourtant, n'est pas à elle.


2. The french students try to say Nihao to me in mandarin as soon as they learn that I am Chinese.

`dès que`, `aussitôt que`, `à peine que`

> Ces étudiants français, dès qu'ils apprennent que je suis chinois, essayent de me dire en chinois << Ni Hao >>.


3. Last week, the department of French language organized an exchange meeting between the french and chinese students. For the Chinese students, it was a rare opportunity to speak to French closely.

`de près`

> La semaine dernière, le département de français a organisé une rencontre entre les étudiants français et chinois. Pour ces derniers, c'est une occasion rare de pouvoir parler d'aussi près avec des Français.


4. I finally realized that the children never considered me as their mother.

`considérer comme`, `se rendre compte de`

> Finalement, je me suis rendu compte que l'enfant, en fait, ne m'avait jamais prise pour sa mère.  
> Finalement, je me suis rendu compte que l'enfant, en fait, ne m'avait jamais considéré comme sa mère.


