---
title: "Lesson 14"
date: "2026-2-12"
categories: ["AF Nice", "B2", "Défi4", "Unit1" ]
reference-location: margin
citation-location: margin
number-sections: false
---

# Standard course

## LE TEXT

### RÉDIGIER UN LETTRE OUVERTE

Lettre ouverte contre le construction d'un nouveau centre commercial
[À Liège, le 27 juin 2018]{style="display: block; text-align: right;"}

Monsieur le Bourgmestre,

J'ai l'honneur de vous écrire au nom de l'asbl Liègeurb pour vous demander de renoncer à la construction du centre commercial "Au bord de quai" sur friche industrielle d'Omni-Tech. En effet, notre association doute de la nécessité de construire un centre commercial supplémentaire. Les arguments à son encontre[^1a1] sont nombreux. 

Tout d'abord, nous tenons à rappeler[^1a2] que plusieurs études socio-économiques indiquent une saturation des zones commerciales en province de Liège. La mutiplication de ces zones en périphérie de la ville a conduit à une augmentation du trafic automobile et à un étalement[^1a3] urbain démesuré[^1a4]. En parallèle, ces denières années, divers centres commerciaux ont été construits au cœur de la ville pour la redynamiser. Mais, ces projets affaiblissent[^1a5] les commerçants indépendants et enlaidissent[^1a6] le paysage[^1a7] urbain. 

[^1a1]: encontre = against, in opposition to
[^1a2]: tenir à rappeler = to want to remind, to wish to recall
[^1a3]: a sprawl, étaler= to spread out, to expand
[^1a4]: excessive
[^1a5]: affaiblir = to weaken 
[^1a6]: enlaidir = to make ugly; laid = ugly (adj.)
[^1a7]: a landscape, a scenery

Sur le plan de[^2a1] la mobilité, nous pensons qu'il est incohérent d'autoriser la construction d'un parking de 2350 places, alors que[^2a2] le conseil communal s'est engagé à diminuer le trafic automobile. C'est d'autant plus inacceptable que[^2a3] cette zone est déjà saturée par la circulation automobile et très bien desservie par les transports public. 

Sur le plan esthétique, il nous paraît[^2a4] infiniment[^2a5] triste de voir une ville tourner le dos à son cours d'eau[^2a6]. Le projet prevoit la construction d'un mur de 20 mètres de haut sur plus de 200 mètres de long des rives[^2a7] de la Meuse. Quelle absurdité pour notre ville qui porte le titre de capitale wallone de l'eau!

[^2a1]: on the level of, in terms of 
[^2a2]: alors que = while, whereas
[^2a3]: it's all the more unacceptable that; d'autant plus (adj.) que = all the more (adj.) that...
[^2a4]: paraître = to seem, to appear
[^2a5]: infinitely 
[^2a6]: la rive = bank, shore; la rivière = river; le rivage = coastline 

Par conséquent[^3a1], nous proposons de réhabiliter cette friche industrielle en y développant un espace vert, ce projet nous semble une initiative susceptible[^3a2] de contribuer au bien-être des Liégois. Par ailleurs, le développement d'un parc au cœur de la ville permettra de réduire la chaleur urbaine tout en créant[^3a3] un lien social. 

En espérant que ces arguments pourront influencer votre décision, nous vous prions de croire[^3a4], Monsieur le Bourgmestre, en notre respectueuse considération[^3a5]. 

Patrice Deweeler, président de l'asbl Liègeurb

[^3a1]: par conséquent = consequently; note conséquent is adj. the noun is conséquence 
[^3a2]: susceptible de = likely to, liable to, capable of 
[^3a3]: tout en créant = all the while creating...; tout en + gérondif = all the while + present participle 
[^3a4]: prier de croire = to beg to believe, to ask to believe
[^3a5]: respectful consideration; respectueux/respectueuse = respectful


## Vocabulaire

- Un bourgmestre (n.m) = a mayor (in Belgium and Luxembourg) 
- Une bourgmestre (n.f)  
- Un magistrat (n.m)   = a magistrate, a judge (in France) 
- Une magistrate (n.f)  
- Un juge (n.m)  
- Une juge (n.f)  
- Un étalement (n.m)  
- Étaler (v.)   
- Laid (adj.)   
- Enlaidir (v.) = to make ugly  
- Un enlaidissement (n.m)  
- Faible (adj.)  
- Faiblir (v.) = to weaken, to become weak  
- Affaiblir (v.)  = to weaken, to make weak  
- Un affaiblissement (n.m)  = a weakening, a decline - Un affaiblissement de la santé, de l'économie, etc.  
- Prendre congé  



## Devoirs

:::{.callout-important}
#### Devoirs

Pour le vendredi 13 février : 

- Revoir les leçons sur les points de grammaire vus cette semaine et le vocabulaire.
- Rédiger une lettre ouverte. 
  - Choisissez un sujet, déterminez un objectif et le destinataire de votre lettre ouverte.
  - Sujets : 
    - [Embellir la ville.]{style="background-color: #90ee90;"}
    - [Rendre la ville plus poétique.]{style="background-color: #add8e6;"}
    - [Interdire la voiture en ville.]{style="background-color: #ffcccb;"}
    - [Créer un péage (toll) urbain.]{style="background-color: #ffeccb;"}
    - [Réglementer la circulation des trottinettes.]{style="background-color: #ff80cb;"} 


**_conseils_**:  

- Respectez les règles formelles de la lettre (destinataire, date, lieu, expéditeur...).  
- Structurez-la en paragraphes (faits, arguments, proposition...) et utilisez des connecteurs logiques.  
- Choisissez soigneusement vos arguments et utilisez-les avec des exemples concrets.  
- Faites des phrases courtes 
- Prenez le temps de faire brouillon. (brouillon = draft)


**_lexique_**: 

Pour commencer la lettre  

- J'ai l'honneur de vous écrire pour vous demander de ...  
- Ce qui motive cette lettre, c'est ...  

Pour présenter les arguments  

- Les arguments à son encontre sont ...  
- Nous tenons à dire / signaler / dénoncer ...  
- Les études indiquent que ...  
- Sur le plan de ... 
- Ces projets contribuent à ...   

Pour exprimer une opinion 

- Il nous paraît triste / évident / scandaleux / essentiel de ...   

Pour proposer  

- Face à ce problème, nous proposons ...  
- Nous souhaitons / demandons que ...  

Pour conclure 

- En espérant que ces arguments pourront influencer ...


:::





>
>**Lettre ouverte pour réglementer la circulation des trottinettes à Pandaville**
>
>[À Pandaville, le 12 fevrier 2026]{style="display: block; text-align: right; font-weight: bold"}
>
**Monsieur le Maire,**
>
J'ai l'honneur de vous écrire au nom de l'association Chevaliers Dragons pour vous demander de réglementer la circulation des trottinettes dans notre ville. Dans le cadre de la loi existant, rien ne régle les utilisations et les gestions de trottinette.  
>
Prémierment, nous tenons à rappeler que plusieurs études indiquent une augmentation de les accidents à cause des trottinettes. L'utilisation de trottinette par le public sans régulations a contribué aux problèmes de sécurité publique. De plus, sans la supervision adéquate, les trottoirs pourraient devenir inaccessibles. 
>
Sur le plan de l'obligation de l'enterprise, nous pensons lorsque une enterprise privée qui conduit et profite de l'opération de trottinettes, celle-ci soit obligée à gérer des parkings ordrés des trottinettes et à assumer les résponsibilités légales en cas des accidents.   
>
Finalement, nous croyons que le gouvernement de la ville est responsable d'assuer la qualité et le recyclage prudent des trottinettes, surtout des batteries. Les trottinettes, c'est une mode écologique de transport. Mais, c'est vrai uniquement si les utilisations sont réglementées efficacement 
>
En espérant que ces propositions pourront influencer votre décisions, nous vous prions de croire, Monsieur le Maire, en notre respectueuse considération.
>
>
>[Maître Shifu, président de la association de Chevaliers Dragons]{style="display: block; text-align: right; font-weight: bold"}






