---
title: "Le Nouveau Taxi 3 - Leçon 13"
date: "2025-10-18"
categories: ["Le Nouveau Taxi", "B1" ]
reference-location: margin
citation-location: margin
---

## Texte

### New York by Jean-Paul Sartre


La nature pèse **si** lourdement[^1a3] sur New York **que** la plus moderne des villes est aussi la plus sale[^1a4].  
Dès la fin de mai, la chaleur **s'abat** sur la ville comme une bombe atomique. C'est le Mal. Les gens **s'abordent** en se disant: « It's a murder. »


Les trains **emportent** des millions[^1b1] de citadins. Ce n'est pas la ville qu'ils **fuient**, c'est la Nature. Jusque[^1b2] dans les **profondeurs** de mon appartement, je **subis** les assauts **d'une nature hostile[^1b3]**, sourde[^1b4], mystérieuse. Je crois camper[^1b5] au cœur d'une jungle grouillante d'insectes[^1b6]. 


Il y a le gémissement[^1c1] du vent, il y a les cafards[^1c2] qui courent dans ma cuisine, les ascenseurs qui **donnent la nausée[^1c3]**, la soif inextinguible[^1c4] qui me brûle[^1c5] du matin au soir. 

Jean-Paul Sartre, Situations, tome III  
Gallimard 1949


:::{.callout-tip}
##### peser
to weigh (consider, in figurative speech)  
- Cette chaise de bois pèse un kilo.  

peser sur = press hard on ...  
- Le baiser[^1a1] de son ami vint[^1a2] peser doucement sur sa bouche.  
- Leurs conseils ont pesé énormément sur notre décision.  
- Son attitude pèse sur ma décision.
:::


:::{.callout-tip}
##### si...que
so ... that.... _Note subjonctif if main clause is negatif_.  
- Il est si faible qu'il ne peut parler.  
- Il n'est pas si faible qu'il ne puise parler.  
- Est-il faible qu'il ne puisse voyager?  
:::

:::{.callout-tip}
##### abattre
knock down, slaughter, attack  
- abattre un arbre  
- abattre un homme grand  
- abattre un adversaire  
- abattre un avion/un oiseau  

##### s'abattre
crash, fall  
- Un mur s'abat brusquement.  
- Un orage s'est abattu. 
:::

:::{.callout-tip}
##### bord
border, edge
- au bord de la mer  
- aborder un port  (border a port)  
- aborder une fille (approach...)   

##### s'aborder
approach each other  
- Les gens s'abordent. 
:::


[^1a1]: kiss
[^1a2]: venir in passé simple 
[^1a3]: si lourdement = so heavily
[^1a4]: dirty


:::{.callout-tip}
##### porter
carry, take away (with you, your body)
- porter un sac, un collier, un bébé

#### emporter
take away (with you)
- Il a emporté un pot de fleurs.
:::

:::{.callout-tip}
##### fuir
flee, run away from
- fuir la ville  
- fuir un danger  
- fuir un pays
:::

:::{.callout-tip}
##### profond,e
deep  
- un puits profond (a deep well)  
- un esprit profond (a deep mind)

#### la profondeur (f.) = depth  
- dans les profondeurs de mon esprit (in the depths of my mind)  
:::

:::{.callout-tip}
##### subir
undergo, suffer  
- subir la violence  
- subir sa mauvaise attitude  
- subir une épreuve (undergo a test)  
- subir les assauts de ... (suffer the attacks of ...)
:::

:::{.callout-tip}
##### une nature hostile, sourde, mystérieuse
Note the "une" here, often used in such a way (une/un + noun + adjectives), even if the noun is sometimes uncountable.
- une eau sans cesse renaissante  
- un soleil brillant  
- Du haut de cette montagne, on découvre un paysage magnifique (From the top of this mountain, one discovers a magnificent landscape).   
- Cette source donne une eau très pure.
:::

:::{.callout-tip}
##### donner la nausée à qn
- Cette odeur me donne la nausée.
:::


[^1b1]: des millions = millions of ...; des centaines de = hundreds of ...
[^1b2]: up to, until
[^1b3]: être hostile à qn/qc
[^1b4]: deaf
[^1b5]: camper = camp
[^1b6]: grouillant de = teeming with, swarming with, similar to "plein de"




[^1c1]: moan, groan, from gémir = to moan, groan
[^1c2]: cockroach
[^1c3]: nausea
[^1c4]: inextinguishable (unquenchable thirst)
[^1c5]: burn, here figurative, talking about a sense of feeling




### New York by Albert Camus

Pluie sur New York. Elle **coule** inlassablement[^1d1] entre les hauts cubes de ciment. Bizarre sentiment **d'éloignement** dans le taxi dont les **essuie-glaces** rapides et monotones **balaient** une eau sans cesse renaissante[^1d2]. 

Impression d'être pris au piège[^1f1] de cette ville et que je pourrais **me délivrer** des blocs qui m'entourent[^1f2] et courir pendant des heures **sans rien** retrouver **que** des nouvelles prisons de ciment sans l'espoir[^1f3] d'une colline[^1f4], d'un arbre vrai ou d'un visage **bouleversé**. 

Pluie de New York. Incessantes, balayant tout. Et dans la brume[^1g1] grise les gratte-ciel[^1g2] **se dressent** blanchâtres[^1g3] comme les immenses sépulcres[^1g4] de cette ville habitée par les morts. Terrible sentiment d'abandon. 

:::{.callout-tip} 
##### couler
flow, run  
- La fleuve coule nuit et jour. (The river flows day and night)  
- Les larmes coulent sur ses joues. (Tears run down her cheeks)
:::

:::{.callout-tip}
##### éloigner 
move away, distance  
- Le souvenir m'a éloigné. (The memory is moving away from me)

##### s'éloigner 
move away oneself, distance oneself  
- Je m'éloigne de ma ville natale. (I am moving away from my hometown)  
-

##### l'éloignement 
(n.) distance, separation, moving away
:::

:::{.callout-tip}
##### essuyer
to wipe  
- essuyer les sueurs (wipe the sweat)   
- essuyer la pluie (wipe the rain)  

##### un essuie-glace
windshield wiper
:::

:::{.callout-tip}
##### balayer
sweep  
- balayer la terre (sweep the floor)  
- balayer les feuilles mortes (sweep the dead leaves)
:::

[^1d1]: tirelessly, incessantly
[^1d2]: renaissante = renewing, reborn, sans cesse = sans arrêt = incessantly


:::{.callout-tip}
##### se délivrer de
to free oneself from
se délivrer de ce fardeau (to free oneself from this burden)  
:::

:::{.callout-tip}
##### sans/ne rien ... que ...
nothing ... but ...
- Je ne pense à rien que de rester avec toi. (I think of nothing but staying with you)  
- Je n'ai rien trouvé que de vieux bouquins. (I found nothing but old books)  
- Je n'ai pas d'autres moyens que de payer par carte bankcaire. (I have no other means but to pay by credit card)
:::

:::{.callout-tip}
##### bouleverser
to turn upside down, to upset, to shake up, to disrupt  
- bouleverser mon plan (to disrupt my plan)  
- Ce changement a bouleversé sa vie.
- un visage bouleversé (here it means "a face showing emotion" disrupted from an emotionless face)
:::


[^1f1]: piège = trap, être pris au piège = to be trapped
[^1f2]: entourer = to surround
[^1f3]: l'espoir (m.) = hope
[^1f4]: hill




:::{.callout-tip}
##### dresser 
to raise, to erect  
- dresser une tente (to pitch a tent)

##### se dresser
to stand up, to rise
:::


[^1g1]: mist, haze, fog
[^1g2]: skyscraper
[^1g3]: blanchâtre = whitish, pale
[^1g4]: sepulchre = tomb, grave


## Thème

1. The skyscraper is in the center of New York City. I hate its color. 

`se situer`, `se trouver`,  
`au centre de`, `au cœur de`

> Le gratte-ciel se situe au centre de New York et je déteste sa couleur. 


2. I like the city you are escaping from. 

> J'aime la ville que tu vas fuir.  
> La ville que tu vas fuir me plaît beaucoup.  


3. His class is so boring that I think most students are sleeping. 

> Son cours est si ennyueux qu'il me semble que la plupart des étudiants dorment.

4. What gives us the sense of happiness is not city life but calm country life.

> Ce qui nous donne le sentiment de bonheur n'est pas la vie urbaine, mais la vie tranquille à la campagne.  
> ce qui nous rend heureux n'est pas la vie citadine, mais la vie rurale. 





