---
title: "2026-06-23 Week 4 Lesson 17"
date: "2026-06-23"
categories: ["bordeaux", "af", "B1", "unite6"]
reference-location: document # margin, block, section, document
citation-location: document #margin
image: "https://images.unsplash.com/photo-1548811579-017cf2a4268b?q=80&w=640"
---

# Le précis

l'écoute: un dialogue au musée  
devoir  


# Grammaire: L'adjectif qualitatif

[Référence aux pages 160 - 161 de livre]{.fst-italic .text-secondary}

- La place de l'adjectif
- Changement de sens de l'adjectif

# Devoir

## Mettres les mots dans l'ordre

a. coloré · il y a · fond · un  
   [Il y a un fond coloré.]{.fst-italic}

b. des · on · très · personnes · voit · souriantes  
   [On voit des personnes très souriantes]{.fst-italic}

c. un · l'homme · fascinant · a · regard  
   [L'homme a un regard fascinant.]{.fst-italic}

d. rayé · porte · il · un · costume  
   [Il porte un costume rayé.]{.fst-italic}

e. son visage · étrange · cache · chapeau · un  
   [Un chapeau cache son visage étrange.]{.fst-italic}

f. noirs · la femme · les · a · cheveux  
   [La femme a les cheveux noirs.]{.fst-italic}

g. porte · elle · superbe · une · robe  
   [Elle porte une robe superbe.]{.fst-italic}

h. sac · tient · elle · petit · un  
   [Elle tient un petit sac.]{.fst-italic}

i. perspective · la photo · belle · une · offre  
   [La photo offre un belle perspective.]{.fst-italic}

j. paisible · on · une · sent · atmosphère    
   [On sent un atmosphère paisible.]{.fst-italic}

















