---
title: "Leçon 33: Raconter une expérience"
date: "2026-07-22"
categories: ["B1", "unite9", "autodidacte"]
reference-location: document # margin, block, section, document
citation-location: document #margin
image: "https://images.unsplash.com/photo-1586022045497-31fcf76fa6cc?q=80&w=640"

---


# Doc1

[La Pacific Crest Trail au féminin, à pied du Mexique au Canada]{.fw-bold .fs-3}

[Traverser les États-Unis à pied et seule du Mexique au Canada sur le Pacific Crest Trail (PCT) : voilà la longue et belle [aventure]{.underline} que Sophie Jacob, 23 ans, a vécue du 31 mai au 13 septembre 2018. Voici son récit.]{.fst-italic .fs-5 .text-blue}

Le PCT est l'un des plus longs [sentiers de randonnée]{.underline} des États-Unis. Il traverse trois États : la Californie, l'Oregon et l'État de Washington. Le PCT, c'est 4 260 km de marche, 131 km de [dénivelé]{.underline}[^aa], et la traversée du désert de Mojave et de deux chaînes de montagnes : la Sierra Nevada et la chaîne des Cascades.


[^aa]: dénivelé (n.m.) : différence d'altitude entre deux points.
[^a2]: au féminin (loc.) : en tant que femme, du point de vue d'une femme.

Je vais essayer de vous raconter en quelques lignes ces 105 jours de marche [au féminin]{.fw-bold}[^a2] et [au cœur de]{.fw-bold} la nature américaine.

Je m'étais longtemps préparée à ce challenge et c'est le 12 novembre 2017 que mon rêve a réellement [pris forme]{.underline}[^ab], quand j'ai obtenu le permis délivré par la PCTA (l'Association du Pacific Crest Trail). Le PCT, c'est un des plus longs [chemins de randonnée]{.underline} mais c'est aussi une aventure humaine.
Je voulais tester mes limites, [affronter]{.underline} la solitude, comprendre ce qui nous lie à la nature et enfin tester ma force mentale et ma détermination.

[^ab]: prendre forme : se concrétiser, se réaliser.
[^az]: s'y faire (loc.) : s'habituer à quelque chose, accepter une situation.


L'avantage de voyager seule, d'être une femme et [en plus]{.fw-bold}[^ac] étrangère, c'est que j'ai reçu beaucoup d'aide ! [Par contre]{.fw-bold}[^ad], en 105 jours je n'ai pu me doucher que 10 fois... Mais on [s'y fait]{.underline}[^az] !

Il faut aussi aimer dormir [au milieu de]{.fw-bold} la nature avec les animaux qui [rôdent]{.underline}[^ae]... les ours, les serpents à sonnette, les pumas et autres. Ma plus grande crainte était justement de [me retrouver face à]{.fw-bold} un ours... [Comme]{.fw-bold} je n'en avais jamais rencontré, [cela m'inquiétait]{.fw-bold}.
Alors au début, dans les zones vraiment [à risques]{.underline}, j'essayais de camper avec d'autres randonneurs pour ne pas avoir de mauvaise surprise comme un ours qui viendrait [renifler]{.underline}[^af] [autour]{.fw-bold} de ma tente. Heureusement, [ça ne m'est jamais arrivé]{.fw-bold}. 

Ma deuxième crainte, c'était les serpents à sonnette. Je [m'étais renseignée]{.underline} et je savais qu'ils étaient dangereux. Et [ça n'a pas manqué]{.fw-bold}[^ag], j'en ai vu des dizaines ! Je n'avais pas imaginé le bruit qu'ils faisaient. La première rencontre a eu lieu au kilomètre 10, [en plein milieu de]{.fw-bold} mon chemin. Il me fixait[^ah]... j'ai fait un immense détour pour le contourner ! J'y repense en souriant car [ça a été là]{.mark} simplement [un pas de côté]{.underline}[^ai] pour les éviter et j'aimais même les observer.

[^ac]: en plus (adv.) : de surcroît, de plus, en outre.
[^ad]: par contre (adv.) : en revanche, plutôt comme "mais"
[^ae]: rôder (v.) : se déplacer sans but précis, en cherchant quelque chose.
[^af]: renifler (v.) : sentir avec le nez.
[^ag]: ça n'a pas manqué (loc.) : cela s'est produit, cela est arrivé (it didn't fail to happen).
[^ah]: fixer (v.) : regarder avec insistance.
[^ai]: un pas de côté (loc.) : a sidestep, a detour.


C'est [vers]{.fw-bold} [la moitié du]{.underline} PCT, kilomètre 2 150, que j'ai rencontré Sauer, un Américain de mon âge, qui parcourait[^ao] [lui aussi]{.mark}[^a5] le PCT en totalité. Lui, il voulait accomplir un défi physique, retrouver la même sensation de liberté qu'il avait eue en traversant les Pyrénées. 
On a très vite [sympathisé]{.underline}[^ap] et on a marché ensemble jusqu'à l'arrivée au Canada ! Ça a été une rencontre incroyable et une belle amitié. Nous avons partagé nos valeurs et notre engagement écologique. Cela reste l'un de mes plus beaux souvenirs, avec l'ascension du mont Whitney à 4 400 m d'altitude (le point culminant des États-Unis [hors Alaska]{.fw-bold}). [En plus de]{.fw-bold} l'exploit[^aq] physique et psychologique, cette expérience m'a encouragée à agir pour la protection de la nature.

[^ao]: parcourir (v.) : traverser, accomplir un trajet
[^ap]: sympathiser (v.) : se lier d'amitié avec quelqu'un.
[^aq]: exploit (n.m.) : action remarquable, difficile à réaliser.
[^a5]: « lui » ici est mis en valeur (HE also...)


# Doc2

::: {.callout-note collapse="true" title="Transcription : partir en voilier autour du monde"}

::::{.fs-5}

[Cécile : ]{.fw-bold .text-green} C'est vous, Pep ?

[Pep : ]{.fw-bold .text-blue} Oui, c'est moi. Bonsoir.

[Cécile : ]{.fw-bold .text-green} Bonsoir. Je m'appelle Cécile. J'ai vu votre annonce sur le [panneau]{.underline} de la librairie. Je voudrais faire un voyage de plusieurs mois. Je suis [étudiante en droit]{.underline}, mais je vais [faire une année de césure]{.underline}.

[Pep : ]{.fw-bold .text-blue} Une année de quoi ?

[Cécile : ]{.fw-bold .text-green} De césure. [C'est-à-dire]{.fw-bold} que je veux faire une pause d'un an pendant mes études.

[Pep : ]{.fw-bold .text-blue} Ah, ok.

[Cécile : ]{.fw-bold .text-green} Donc, vous cherchez des personnes pour partir en mer avec vous ? Vous pouvez m'en dire plus ?

[Pep : ]{.fw-bold .text-blue} Avec plaisir. On [se tutoie]{.fw-bold} ?

[Cécile : ]{.fw-bold .text-green} D'accord.

[Pep : ]{.fw-bold .text-blue} Alors moi, j'ai acheté [un voilier]{.underline} qui est dans le port de Lisbonne. Là, je suis à Paris pour vendre mon appartement et [régler quelques affaires personnelles]{.underline} [avant de partir]{.fw-bold .text-pink} pour un an [autour du monde]{.underline}. Un bateau de 12 mètres, c'est assez grand. Et donc, je cherche des [équipiers]{.underline} et des équipières. Et [dès que]{.fw-bold .text-pink} j'ai trouvé [l'équipage]{.underline}, c'est-à-dire trois personnes, je retourne à Lisbonne et je [mets le cap sur]{.underline}[^da] les Açores, puis la Guadeloupe, etc.

[^da]: mettre le cap sur (loc.) : diriger le bateau vers une destination.


[Cécile : ]{.fw-bold .text-green} Et vous avez... Enfin, tu as déjà fait un aussi long voyage ? Et tu sais [naviguer]{.underline} ?

[Pep : ]{.fw-bold .text-blue} [Autrefois]{.fw-bold}, quand j'étais très jeune, j'ai [longé la Patagonie à la voile]{.underline}. [Ça fait deux ans]{.fw-bold} que je me prépare. Et j'ai aussi [suivi une formation]{.underline}[^db] en Bretagne.

[Cécile : ]{.fw-bold .text-green} Et pourquoi tu veux faire [le tour du monde]{.underline} ?

[Pep : ]{.fw-bold .text-blue} J'ai décidé d'arrêter de travailler [après que]{.fw-bold .text-pink} mon médecin m'a alerté. Il m'a dit que je risquais le burn-out. Comme j'avais 59 ans, j'ai [démissionné]{.underline}. Je veux profiter du temps que j'ai. [M'échapper]{.underline}[^dc] de la ville. Être proche de la nature.

[Cécile : ]{.fw-bold .text-green} Wow ! Quelle décision !

[Pep : ]{.fw-bold .text-blue} [Au moment où]{.fw-bold .text-pink} j'ai décidé de [tout plaquer]{.underline}[^dd], je [me suis senti]{.underline} libéré. [Avant que]{.fw-bold .text-purple} le boulot [devienne]{.text-purple} vraiment stressant, j'étais plutôt heureux. J'ai beaucoup travaillé, j'ai gagné beaucoup d'argent, mais aujourd'hui, ça ne m'intéresse plus. Et toi ? Pourquoi tu veux partir ?

[Cécile : ]{.fw-bold .text-green} J'[ai envie de]{.underline} voyager, mais [sans faire]{.fw-bold} du tourisme. Je veux découvrir le monde et [savoir de quoi]{.underline} je suis capable. Mais [avant de]{.fw-bold .text-pink} me décider, j'ai besoin d'un peu plus d'infos. Je ne connais rien à la navigation. Est-ce qu'il faudrait que je suive une formation ? Est-ce qu'on est payé ?

[Pep : ]{.fw-bold .text-blue} T'as pas besoin de formation. Et personne n'est payé. Tout le monde participe au travail. Cuisiner, réparer, [manœuvrer]{.underline} et nettoyer. [Il y a beaucoup à faire]{.underline} [sur]{.fw-bold} un bateau. Et quand quelque chose [casse]{.underline}, il faut réparer [avant qu]{.fw-bold .text-purple}'il fasse nuit. [Pendant que]{.fw-bold .text-pink} [les uns]{.markgreen} travaillent, [les autres]{.markgreen} dorment. On n'arrête jamais. Et pendant les [escales]{.underline}[^de], on fait les courses, on visite un peu et on repart.

[Cécile : ]{.fw-bold .text-green} Tu penses que ce serait difficile pour moi ?

[Pep : ]{.fw-bold .text-blue} Je ne sais pas. Ça [dépend de]{.fw-bold} toi.

[Cécile : ]{.fw-bold .text-green} J'aimerais tellement me retrouver au milieu de l'océan. Mais j'ai un peu peur en même temps. Puis... je sais pas.


[^db]: suivre une formation (loc.) : suivre un cours pour apprendre quelque chose. formation (n.f.) : cours, enseignement, apprentissage.
[^dc]: s'échapper (v.) : fuir, se libérer d'une situation.
[^dd]: tout plaquer (loc.) : abandonner son travail, sa vie, ses habitudes. plaquer (v.) : abandonner, laisser tomber.
[^de]: escale (n.f.) : arrêt d'un bateau dans un port pour se ravitailler ou faire une pause.

::::
:::

<audio controls style="width:95%">
  <source src="https://inspire.hachettefle.fr/dl.php?f=ressources/INSP3_LE_AUDIO/INSP3_LE_Piste139.mp3" type="audio/mpeg">
</audio>



# Grammaire


:::{.bg-red .rounded-3 .shadow .m-1 .p-2}

[Les temps du récit au passé]{.fw-bold .fs-5}

- **Le passé composé** : pour parler [d'un événement ou d'un fait ponctuel]{.underline} et pour exprimer [un succession d'actions]{.underline}.
- **L'imparfait** : pour décrire [les circonstances]{.underline} d'un événement ou d'un fait ponctuel, faire une [description]{.underline} ou raconter des [habitudes]{.underline}.
- **Le plus-que-parfait** : pour exprimer une action passée antérieure à une action passée.

:::

### Ex. 1 : Complétez le témoignage avec les verbes au passé composé, à l'imparfait ou au plus-que-parfait

:::{.border .shadow-sm .m-2 .p-2 .marksilver .fs-5}

L'hiver dernier, je [me suis inscrit]{.text-orange} (s'inscrire) à l'Ultra Trail du Mont-Blanc (UTMB) et je [ai couru]{.text-orange} (courir) 168 kilomètres autour du Mont-Blanc avec un dénivelé de 9 600 mètres. Avant de faire cette course, je [n'avais jamais couru]{.text-orange} (ne jamais courir) aussi longtemps. Il y [avait]{.text-orange} (avoir) 2 500 coureurs. Je [m'étais preparé]{.text-orange} (se préparer) longtemps à l'avance pour être en forme car je [savais]{.text-orange} (savoir) que j'allais courir pendant 40 heures. 

On [a quitté]{.text-orange} (quitter) Chamonix le vendredi à 17 h 30 et malheureusement il ne [faisait]{.text-orange} (faire) pas très beau : alors que le soleil [a brillé]{.text-orange} (briller) les deux jours précédents, il [s'est mis]{.text-orange} (se mettre) à pleuvoir au moment où nous [sommes partis]{.text-orange} (partir). Et il [a plu]{.text-orange} (pleuvoir) pendant les quatre premières heures de course. La fatigue [a commencé]{.text-orange} (commencer) à se faire sentir au bout de 10 heures de course. De plus, je [m'étais blessé]{.text-orange} (se blesser) à la cuisse trois jours avant et la douleur [est revenue]{.text-orange} (revenir) pendant une descente. À la première grande pause, je [ai mangé]{.text-orange} (manger) une grande assiette de pâtes et je [suis reparti]{.text-orange} (repartir). Il [restait]{.text-orange} (rester) 122 kilomètres et je [avais]{.text-orange} (avoir) envie d'abandonner. Je [ai trouvé]{.text-orange} (trouver) la force mentale au fond de moi et je [ai continué]{.text-orange} (continuer). Mais ma cuisse me [faisait]{.text-orange} (faire) de plus en plus mal et, en arrivant à une étape, je [me suis dirigé]{.text-orange} (se diriger) vers la tente des soigneurs. Un médecin me [a ausculté]{.text-orange} (ausculter) et me [a autorisé]{.text-orange} (autoriser) à repartir en me conseillant de ralentir un peu. Je [souffrais]{.text-orange} (souffrir) mais je [voulais]{.text-orange} (vouloir) tester mes limites. Je [ai marché]{.text-orange} (marcher) pendant les 50 derniers kilomètres mais je [n'ai pas renoncé]{.text-orange} (ne pas renoncer). Je [ai passé]{.text-orange} (passer) la ligne d'arrivée épuisé mais heureux !


:::


------

# Cahier d'activités

## Ex. 1

::: {.callout-note collapse="true" title="Transcription : voyage insolite en Amérique du Sud"}

::::{.fs-5}

[Le journaliste : ]{.fw-bold .text-green} Bonjour à toutes et à tous. Aujourd'hui, dans notre émission Voyage insolite, nous recevons Salma Boussif, qui revient d'un long voyage. Bonjour Salma, pourquoi avez-vous choisi de voyager ?

[Salma : ]{.fw-bold .text-blue} Quand j'étais jeune, j'avais un rêve. Je voulais voyager pendant plusieurs mois. Mais je n'avais pas d'argent. Après mes études, j'ai dû commencer à travailler. J'avais 23 ans. Je me suis dit que je ne pourrais jamais prendre une année de césure, puisque j'avais déjà démarré dans la vie active. Pourtant, je n'ai pas abandonné cette idée. J'ai pu faire des économies, et huit ans plus tard, étant célibataire, j'étais prête à partir. J'ai quitté mon travail, après que l'entreprise qui m'employait m'a donné un congé, et je suis partie.

[Le journaliste : ]{.fw-bold .text-green} Comment avez-vous préparé votre voyage ?

[Salma : ]{.fw-bold .text-blue} Pendant que je travaillais, j'ai commencé à penser à mon voyage, à ce que je voulais faire. J'ai décidé de voyager en Amérique du Sud, parce que je parlais espagnol, et que j'avais envie de découvrir cette partie du monde. Je voulais visiter plusieurs pays et faire de la randonnée. Il y a de magnifiques sites naturels dans cette région du monde.

[Le journaliste : ]{.fw-bold .text-green} Vous n'avez jamais eu peur de la solitude ?

[Salma : ]{.fw-bold .text-blue} Non. Mes amis étaient déjà en couple, ou formaient une famille, les célibataires travaillaient. Si je voulais voyager, il fallait que je le fasse seule. Avant que je parte, plusieurs personnes de ma famille ont essayé de me décourager. J'ai senti que les autres avaient une crainte, mais moi pas. Après mon retour, ils ont été très heureux pour moi.

[Le journaliste : ]{.fw-bold .text-green} Comment s'est passé votre voyage ?

[Salma : ]{.fw-bold .text-blue} Ça a été un moment de vie extraordinaire. J'étais libre et sans contrainte. Je suis partie six mois, parce que j'avais juste assez d'argent pour ça. Au moment où je suis montée dans l'avion, j'ai ressenti une grande liberté. Quand on a le temps de voyager, on peut s'arrêter dans les endroits qui nous plaisent. On n'est pas obligé de suivre un programme. C'était une expérience incroyable.

[Le journaliste : ]{.fw-bold .text-green} Qu'est-ce qui vous a le plus marqué ?

[Salma : ]{.fw-bold .text-blue} Avoir du temps. Dans notre vie quotidienne, nous sommes toujours pressés. Pendant que je voyageais, le temps ne passait pas de la même façon. J'ai aimé ce rythme lent. Et puis, l'accueil et la gentillesse des gens que j'ai rencontrés. Et aussi, avoir la chance d'aller dans des endroits très isolés, peu connus. J'ai traversé la forêt amazonienne sur un petit bateau et j'étais la seule touriste.

[Le journaliste : ]{.fw-bold .text-green} Quelle aventure ! Vous avez pensé à votre prochain voyage ?

::::
:::

<audio controls style="width:95%">
  <source src="https://inspire.hachettefle.fr/dl.php?f=ressources/INSP3_CA_AUDIO/INSP3_CA_Piste80.mp3" type="audio/mpeg">
</audio>



## Ex. 9

::: {.callout-note collapse="true" title="Transcription : les propositions de temps"}

::::{.fs-5}

1. Au moment où les voyageurs sont arrivés au port.
2. Avant qu'elles partent en voyage.
3. Après que la tempête est passée.
4. Au moment où j'ai pris ma décision.
5. Dès que tu recevras ton passeport.
6. Avant que nos enfants reviennent à Paris.
7. Pendant que vous prépariez les bagages.

::::
:::

<audio controls style="width:95%">
  <source src="https://inspire.hachettefle.fr/dl.php?f=ressources/INSP3_CA_AUDIO/INSP3_CA_Piste81.mp3" type="audio/mpeg">
</audio>


## Ex. 10 Dictée

::: {.callout-note collapse="true" title="Transcription : dictée"}

::::{.fs-5}

a. Dès qu'il aura trouvé un équipage, il quittera son emploi pour faire le tour du monde sur un voilier.
b. J'avais beaucoup de craintes avant que vous me racontiez votre voyage.
c. Il a rangé les affaires pendant que je préparais l'itinéraire.
d. Nous sommes arrivés au moment où la course a commencé.
e. Il lui avait fallu beaucoup de temps pour décider d'accomplir cet exploit.
f. Nous avons terminé l'ascension après que vous êtes parti.
g. J'avais peur d'affronter des problèmes avant d'entreprendre cet exploit.
h. L'équipage a navigué pendant plus d'un an.

::::
:::

<audio controls style="width:95%">
  <source src="https://inspire.hachettefle.fr/dl.php?f=ressources/INSP3_CA_AUDIO/INSP3_CA_Piste82.mp3" type="audio/mpeg">
</audio>


## Ex. 11

:::{.marksilver .text-orange .fs-5 .fst-italic .border .shadow-sm}
Racontez votre voyage le plus marquant. Enregistrez-vous.
:::

:::{.callout-note}
#### ✍️


:::



