---
title: "Le Nouveau Taxi 3 - Leçon 12"
date: "2025-10-14"
categories: ["Le Nouveau Taxi", "B1" ]
reference-location: margin
citation-location: margin
---

## Texte

### Francos utiles

:::{.aside}

un livret / un pamphlet = a booklet / a pamphlet,
notice "et" makes them "little" books.
:::

#### Comment venir[^1a1]?

##### En train:
La Rochelle à 3h de Paris[^1a2], 2h de Bordeaux, 2h de Nantes, 1h30 de Poitiers.

##### En voiture:
La rochelle à 4h40 de Paris, 2h de Bordeaux, 2h de Nantes et 1h30 de Poitiers.

##### Pensez aussi au covoiturage!
Inscrivez-vous sur internet ...  
ou par téléphone: ...  
en collaboration avec Ecolutis.com.

:::{.callout-tip}
#### penser à qch, penser à faire qch
to remember to do something, to think about something  
- Il faut penser à notre demande.  
- Pensez à éteindre la lumière. (remember to turn off the light)
:::


:::{.callout-tip}
#### en collaboration avec ...
in collaboration with ...  
- La Société des Francofolies organise le festival en collaboration avec Ecolutis.com pour le co-voiturage.  
- Plusieurs pays africains améliorent leur infrastructure en collaboration avec des sociétés chinoises.
:::


[^1a1]: comment/pourquoi/quand/que + verbe infinitif, a brief informal way of asking for or giving information.
[^1a2]: à ... de ... indicating distance between two places.


#### Où dormir?

L'Office du Tourisme vous renseigne  
Quartier du Gabut - Face à l'aquarium  
L'office du tourisme met à votre disposition une liste des hébergements (hôtels, campings...)

#### offre spéciale Francofolies
Découvrez les offres Billet + Bus ou Billet + Hôtel ...

#### Les Francos vous facilitent la vie!
Un hébergement de dernière minute via les CEMEA (accueil 24h/24, 7j/7)

##### Terrain d'accueil provisoire à la SCAN
Espace jeune: 2 euros la nuit par emplacement[^1b1] de tente, sans réservation.

##### Terrain d'accueil provisoire << Le petit Marseille >>
Espace groups encadrés: 2 euros la nuit par personne  
Espace famille: 2 euros la nuit par personne  

Consigne gratuite[^1c1]:  
A l'entrée de l'Esplanade St Jean d'Acre sur présentation de votre place de concert.

Personne à mobilité réduite:  
pour améliorer votre accueil lors de votre venue, merci de vous signaler au ...






:::{.callout-tip}
#### renseigner qn (sur qch)
to inform someone (about something)  
- L'Office du tourisme de la Rochelle peut renseigner les spectateurs des Francofolies sur les possibilités d'hébergement (hébergement = accommodation).  
- S'il vous plait, pourriez-vous me renseigner sur les nouveaux horaires de train Paris-La Rochelle?

se renseigner (sur qch) - to find out (about something)   
- Je voudrais me renseigner sur les possibilités d'hébergement à La Rochelle.
:::

:::{.callout-tip}
#### mettre qch à la disposition de qn
to make something available to someone  
- L'école a mis à la disposition des élèves une trentaine d'ordinateurs.  
- Un numéro vert est mis à la disposition des habitants. (a toll-free number is made available to residents. In France, toll free numbers are color coded green.)  
- Je suis toujours à votre disposition. 
:::

:::{.callout-tip}
#### partir en live
to go off the rails, to go crazy (informal)  
- Hier soir, la fête est partie en live!

however, _en live_ = live (as in a live performance)
:::

:::{.callout-tip}
#### faciliter qch à qn
to make something easier for someone  
- Les transports en commun nous facilitent la circulation en ville. (Public transport makes it easier for us to get around the city.)
:::

:::{.callout-tip}
#### provisoire
temporary, provisional  
- une solution provisoire (a temporary solution)  
- un emploi provisoire (a temporary job)  

opposite of: permanent
:::

:::{.callout-tip}
#### encadrer qn/qch
to supervise, to frame
- encadrer des groupes d'enfants (to supervise groups of children)
- des élèves encadrés (supervised students)
:::

:::{.callout-tip}
#### sur qch...
on, about, over. If followed by a noun, do not use particle  
- Vous pourrez utiliser des casiers de consigne gratuite à l'entrée de l'Esplanade St Jean d'Acre sur presentation de votre place de concert.  
- On propose aussi des visites du château, mais sur réservation uniquement.
:::


[^1b1]: un emplacement = placement, site
[^1c1]: une consigne = a locker, storage


## Thème


1. The young man got lost in this foreign city. Eventually, a homeless man pointed him to the right direction.

>
    - Ce jeune homme s'est perdu dans cette ville étrangére et un mendiant lui a indiqué le chemin.


2. The hotel offers wifi and swimming pool access for free.

>
    - L'hôtel met à votre disposition des services gratuits tels que le wifi, la piscine, etc.


3. Hello! I would like to inquire about any new information regarding the college entrance exam.

>
    - Bonjour! Je voudrais me renseigner sur les nouvelles du bac de cette année.

4. This railroad greatly improved the convenience of living and working of local residents.

>
    - Ce chemin de fer facilite en grande partie la vie et le travail des habitants.


