---
title: "Lesson 17"
date: "2026-2-17"
categories: ["AF Nice", "B2", "Défi4", "Unit2" ]
reference-location: margin
citation-location: margin
number-sections: false
---

# Standard course

## LE TEXT


### LE FORUM DE L'AGRICULTURE AFRI-SAINE

Même si l'Afrique utilise moins de pesticides qu'ailleurs dans le monde, ces faibles quantités présentent un risque très élevé pour la santé et l'environnement. La première démarche[^1a1] consiste donc à limiter l'utilisation à ces produits, et cela passe évidemment par la sensibilisation de la population. C'est ce que fait PAN Africa en éditant et diffusant ces affiches. Et vous? Que pensez-vous de l'usage des pesticides? Participez au débat sur ce forum. 

**_Nadège:_**  

>
Je suppose que la toxicité des pesticides est connue dans les pays européens. Au Burkina Faso, leurs conditions d'utilisation font froid dans le dos[^1a2]. À ce qu'il paraît, la moitié[^1a3] des vendeurs et des agriculteurs ne savent pas ni lire ni écrire, ils ignorent le nom des produits qu'ils utilisent... Ça me révolte[^1a4]! J'ai aussi lu un reportage sur xxxxxx à propos de l'expérience du coton transgénique menée au Burkina Faso. En principe, ça devait enrichir les paysans en leur faisant économiser sur l'engrais[^1a5] et les pesticides. Tu parles! Beaucoup se sont retrouvés sur la paille[^1a6] (sans jeu de mots). J'en veux terriblement à tous ceux qui pensent plus au profit qu'aux humains[^1a7] (Monsanto, l'État, la liste serait longue...).


[^1a1]: first step. démarche: approach, process, step.
[^1a2]: faire froid dans le dos: send chills down the spine, be scary.
[^1a3]: à ce qu'il paraît: apparently, it seems that. moitié = half.
[^1a4]: ça me révolte: it makes me angry, it outrages me.
[^1a5]: faire économiser: save, make save. engrais = fertilizer.
[^1a6]: se retrouver sur la paille: be broke, be penniless. paille = straw. Tu parles! = You can say that again! No kidding!
[^1a7]: en vouloir à quelqu'un: be angry with someone. 

**_Zakaria:_**  

>
Au risque de choquer, je crois qu'il ne faut pas complètement diaboliser les pesticides. Je vous rappelle que le secteur agricole constitue la principale source de revenus environ 90% des Burkinabés. Comment voulez-vous que la population se nourisse si on ne protège pas les cultures? Sans parler du fait que les pesticides tuent les moustiques, porteurs[^2a1] de maladies mortelles[^2a2]...

[^2a1]: porteur: carrier (of diseases).
[^2a2]: mortel: deadly, fatal.


**_Maïmouna:_**  

>
À mon sens, ce qui est révoltant, c'est que certains pesticides sont interdits en Europe depuis longtemps, mais continuent d'être vendus et utilisés en Afrique. J'halucine[^3a1] quand j'entends que le coût total des maladies et des blessures[^3a2] liées[^3a3] aux pesticides pourrait atteindre[^3a4] 90 milliards[^3a5] de dollars d'ici 2020. C'est intensé! Rien que ça[^3a6], ça devrait faire réfléchir, non?

[^3a1]: halluciner: be amazed, be shocked
[^3a2]: injuries.
[^3a3]: lié à: related to, linked to.
[^3a4]: reach, attain
[^3a5]: billion, mille = K, million = M, milliard = B.
[^3a6]: Rien que ça = Just that, That alone.


**_Aboubakar:_**  

>
J'admets[^4a1] que les pesticides facilitent le travail des agriculteurs, mais il est indéniable qu'ils sont noctifs[^4a2] pour l'humain! Il est évidemment indispensable de sensibiliser les populations[^4a3], mais c'est insuffisant. Selon le docteur Hubert Bationo, de l'université de Ouagadougou, il faut encourager la recherche sur les biopesticides et promouvoir[^4a4] ceux qui sont déjà connus. Sauf erreur de ma part[^4a5], c'est déjà le cas dans certains pays, notamment le Bénin. Prenons exemple sur eux!

[^4a1]: admettre = admit, acknowledge.
[^4a2]: nocif = harmful, detrimental
[^4a3]: sensibiliser les populations = raise awareness among the population. sensibiliser = raise awareness.
[^4a4]: promouvoir = promote, encourage.
[^4a5]: sauf erreur de ma part = unless I'm mistaken


## LA GRAMMAIRE

### Pour exprimer la subjectivité on peut utiliser

- La ponctuation : 
  - Les points de suspension: ... 
  - Le point d'exclamation !
  - Le point d'interrogation ?

- Des verbes :   
  - [reconnaître]{.mark}: to recognize, to admit, to acknowledge  (similaire à admettre)
  - [imaginer]{.mark}: (similaire à supposer)
  - [estimer]{.mark}: to estimate  
  - [admettre]{.mark}  
  - [supposer]{.mark}  
  - [révolter]{.mark}: to revolt, to outrage  
  - [choquer]{.mark}: to shock, to offend  

- Des adjectifs :  
  - [intolérable]{.mark}  
  - [absurde]{.mark}  
  - [scandaleux]{.mark}  
  - [insensé]{.mark}: senseless, absurd, insane  
  - [inadmissible]{.mark}: unacceptable
  - [insuffisant]{.mark}  

- Des adverbes : 
  - [absolument]{.mark}  
  - [probablement]{.mark}  
  - [terriblement]{.mark}: very much, terribly  
  - [complètement]{.mark}  
  - [évidemment]{.mark}: obviously  
  - [notamment]{.mark}: notably, especially  

- Des expressions pour:  
  - nuancer un propos:   
    - [d'après ce qu'on dit]{.mark}: from what people say, according to what people say  
    - [si je ne me trompe pas]{.mark}: if I'm not mistaken  
    - [sans vouloir heurter]{.mark}: without wanting to hurt (someone's feelings), _eg. sans vouloir heurter les agriculteurs, je pense que..._  
    - [sauf erreur de ma part]{.mark}: unless I'm mistaken, _eg. sauf erreur de ma part, c'est déjà le cas dans certains pays..._  
    - [au risque de choquer]{.mark}: at the risk of shocking, _eg. au risque de choquer, je crois qu'il ne faut pas complètement diaboliser les pesticides..._  
    - [à ce qu’il paraît]{.mark}: apparently, _eg. à ce qu'il paraît, la moitié des vendeurs et des agriculteurs ne savent pas ni lire ni écrire..._  

  - exprimer son opinion :   
    - [pour moi]{.mark}  
    - [à mon avis]{.mark}: in my opinion  
    - [à mon sens]{.mark}: in my opinion, to my mind  
    - [je crois que]{.mark}  

  - exprimer un sentiment fort :   
    - [je rêve!]{.mark}: I can't believe it!, No way! (usually negative). _eg. Je rêve! Comment peut-on vendre des produits interdits en Europe à des populations qui ne sont pas informées des risques?_  
    - [c’est une blague ?]{.mark}: Is this a joke? (blague: joke)  
    - [ça me scandalise]{.mark}: It scandalizes me, it makes me angry. _eg. Ça me scandalise[^F1] que les pesticides soient interdits en Europe mais continuent d'être vendus et utilisés en Afrique._
    - [je suis en colère contre]{.mark}  
    - [j’en veux terriblement à qqn]{.mark}: I am very angry with someone. _eg. J'en veux terriblement à tous ceux qui pensent plus au profit qu'aux humains._
    - [c’est inadmissible]{.mark}  
    - [c’est insensé]{.mark}
    - [ça me révolte!]{.mark}: It makes me angry, it outrages me. _eg. Ça me révolte que certains pesticides soient interdits en Europe depuis longtemps, mais continuent d'être vendus et utilisés en Afrique._

  - dire qu'on ne dit pas :  
    - [je ne parlerai pas de]{.mark}: I'm not going to talk about... _eg. Je ne parlerai pas de Monsanto, mais c'est un exemple parmi tant d'autres..._
    - [je n'en dis pas plus]{.mark}: I won't say more. _eg. Je n'en dis pas plus, mais c'est un sujet qui me tient à cœur..._

  - contester :  
    - [mon cil!]{.mark}: I don't believe it!, No way! (literally: my eyelash). _eg. Mon cil! Comment peut-on vendre des produits interdits en Europe à des populations qui ne sont pas informées des risques?_
    - [mon oeil!]{.mark}: same as mon cil! (literally: my eye)
    - [tu parles!]{.mark}: You can say that again! No kidding! _eg. Tu parles! Beaucoup se sont retrouvés sur la paille (sans jeu de mots)._ (sans jeu de mots = no pun intended)


[^F1]: Note here it's the verb "scandaliser". It's different from the "Ça me rend + adj" structure.

## VOCABULAIRE

- Ne pas voir le temps passer (= so absorbed in something that you don't notice the time passing)  
- Semer (= to sow, to plant, e.g. semer des graines)  
- Pousser quelqu’un à faire quelque chose (= to push someone to do something)  
- La nostalgie (n.f)  
- Être nostalgique (adj.)  
- Malsain (adj.) / malsaine (adj.) (= unhealthy)  
- Suivre les bonnes pratiques / les bons procédés  ( = to follow good practices)
- Un bénéfice (n.m)  


## DEVOIRS

:::{.callout-important}
##### Devoirs
Pour le mercredi 18 février  
Faire l’exercice de la page suivante.  
Production écrite : Choisissez un sujet et développez votre colère !  

> Les voitures de luxe - Les jeux Olympiques - Les nouvelles technologies - Mon beau-père / Ma belle-mère - Les extraterrestres - Autre

:::


> 
En l'esprit de persister dans mes désagrément aux trottinettes à Pandaville, je continue d'exprimer mes reproches sur ceux. Á mon sens, bravo pour choisir une mode de transport probablement plus écologique, mais plusieurs des gens qui utilisent les trottinettes ne les retournent pas aux lieux désignés. 
C'est intensé qu'on aille trouver chaque jour quelques trottinettes laissées dans les trottoirs, voire complètement bloquant les passes. Comment pouvait-on quelqu'un handicapé passer? Ce sont des gens qui considérent personne que eux-mêmes. Ça me révolte! Au risque de choquer, je crois que chaque personne a autant de besoins que de résponsabilités pour garder l'ordre d'espaces publiques. Alors, tous les citoyens de Pandaville, vous pouvez faire mieux!


