---
title: "2026-06-09 Week 2 Lesson 7"
date: "2026-06-09"
categories: ["bordeaux", "af", "B1", "unite4"]
reference-location: document # margin, block, section, document
citation-location: document #margin
image: "https://images.unsplash.com/photo-1775327278580-0d21cebf58b7?q=80&w=640"
---

# Le précis

Les lexiques de la santé, de la bien-être et de loisirs  
Pratiquez la négation  
Formulez des questions formelles



# Formulez les questions formelle

- Que fait-tu le samidi soir?
- Comment trouves-tu le jardinage?
- Être-vous sorties le weekend denièr?
- Combien d'heures de lecture par semaine crois-tu pour être considé comme un grand lecteur?
- Que pense-tu de la qualité de la litérature contemporaine?



# Lexique


:::{.column .markyellow width="98%"}

- Il est démontré que  
- Il est prouvé que  
- Cette activité est une grande importance pour ...  
- Elle réduit / diminue / atténue + nom   
- Elle permet de + infinitif  
- Elle augemente / développe + nom
- C'est bénéfique pour + nom
- Elle prévient + nom (prevent) 
- Elle entretient + nom (maintain)
- ça marche / c'est très efficace!
- ça nous rend + adjectif
- ça fait du bien à + nom / c'est bon pour + nom
- grâce à + nom

:::

:::{.column}
:::

:::{.column .markyellow width="98%"}


- les capacités respiatoires, cognitives
- la détérioration 
- la sératonine
- plusieurs avantages 
- le sens du beau, de la vision
- un effet apaisant
- atténuer l'anxiété, le stress
- la signature de notre mode
- l'esprit communautaire / d'equipe
- le renforcement musculaire
- un moment de joie, de célébration
- qui unit le monde entier 
- prendre le temps
- se libérer du stress

:::

:::{.column}
:::

:::{.column .markyellow width="98%"}

- "avoir les orteils dans le sable"
- "avoir la tête au boulot"
- "rester connecté" = "accroché"
- "se déconnecté du travail" = "décrocher"
- une incitation / être incité
- des sollicitations

:::


# La négation

Observez les phrases suivantes:<br><br>  

:::{.column .markorange width="98%"}

::::{.columns .text-center}

:::::{.column .text-center width="47%"}

Je **ne** travaille **pas**.  
Je **ne** rencontre **personne**.  
Je **ne** fais **rien**.  
Je **ne** pars **jamais**.  

:::::

:::::{.column .text-center width="47%"}

**Personne ne** vient chez moi.  
**Rien ne** se passe.  

:::::

<br>

En vacances, je **ne** fais **ni** le ménage **ni** les courses.  
**Ni** le sport **ni** la lecture **ne** me plaisent.

::::

:::

:::{.callout-important}
#### La négation

- Pour une personne --> [**ne...personne**]{.text-red}/[**personne...ne**]{.text-red}  
  Il [**n'**]{.text-red}y a [**personne**]{.text-red} d'autre que vous.  
  [**Personne**]{.text-red} d'autre [**n'**]{.text-red}est ici.

- Pour une chose --> [**ne...rien**]{.text-red}/[**rien...ne**]{.text-red}  
  Vous [**ne**]{.text-red} m'avez [**rien**]{.text-red} dit.  
  [**Rien**]{.text-red} ne va.

- Pour deux choses ou deux personnes --> [**ne...ni...ni**]{.text-red}/[**ni...ni..ne**]{.text-red}  
  [**Ne**]{.text-red} revenez pas, [**ni**]{.text-red} ici [**ni**]{.text-red} à la campagne.  
  [**Ni**]{.text-red} la ville [**ni**]{.text-red} la campagne [**ne**]{.text-red} me plaisent.

❗[**ne...jamais**]{.text-red} != toujours : Vous [**ne**]{.text-red} me dites [**jamais**]{.text-red} la vérité. != Vous me dites toujours la vérité.

❗[**Jamais**]{.text-red} peut aussi s'utiliser seul:  
- Tu lis à la plage?  
- [**Jamais**]{.text-red}! 

:::





