---
title: "Le Nouveau Taxi 3 - Leçon 10"
date: "2025-10-8"
categories: ["Le Nouveau Taxi", "B1", "les pronoms complément" ]
reference-location: margin
citation-location: margin
---


## Grammaire - Les pronoms compléments: des verbes qui n'utilisent pas de COI

### à + qch - y

J'ai pensé à une idée.  
→ J'y ai pensé.

Il a réfléchi à cette proposition.  
→ Il y a a réfléchi.

### à + qn - les pronoms COI (me, te, lui, nous, vous, leur)

Je lui ai donné un livre.  
Il m'a offert un cadeau.  
Nous leur avons raconté cette histoire.  

### à + qn - les pronoms toniques (moi, toi, lui, elle, nous, vous, eux, elles)

Remember these verbs use pronoms toniques, not COI pronouns:  
- penser à  
- songer à  (to think about)
- avoir affaire à (to deal with)  
- faire attention à (to pay attention to)  
- être à qn (to belong to someone)

Je pense à elle.  
J'ai eu affaire à lui.  
Cette voiture est à moi. 

_Note the à [tonic] are always after these verbs._

### à + qn - verbes reflexifs, always use tonic

e.g.  
se fier à (to trust)  
s'habituer à (to get used to)  
s'intéresser à (to be interested in)  
se référer à (to refer to)  
s'opposer à (to oppose)  
s'adresser à (to address)  
... etc.  

Je m'intéresse beaucoup à lui.  
Adressez-vous à elle, s'il vous plaît.

_Note the à [tonic] are always after these verbs._

## Entraînez-vous

- Dites-moi, << Luca >>, c'est votre véritable nom?  
- Mais oui, ce nom je (1)_______ ai hérité de mes parents et j'(2)_______ tiens beaucoup. Pour rien au monde je ne (3)______ changerai!  
- Seriez-vous d'accord pour dire que votre succès, vous (4)______ devez en partie[^5a1] à votre imprésario Johnny Res qui a disparu tragiquement l'été dernier?  
- Oui, bien sûr, je (5)______ dois tout et je pense tous les jours à (6)______ . Ne plus (7)______ voir, ça, je ne m'(8)______ habitue pas!  
- Certains professionnels du spectacle n'ont pas été tendre avec vous, vous (9)______ en voulez?  
- Non, je ne m'intéresse pas à (10)______ et je (11)______ laisse le choix général, qu'elles soient bonnes ou mauvaises, je n'(12)______ fais pas attention.  

>
1. l'  
2. y (tenir à qch: to care about something)  
3. le (devoir qch à qn/qch: to owe something to someone/something)  
4. le  
5. lui  
6. lui  
7. le  
8. y (s'habituer à qch: to get used to something)
9. leur (en vouloir à qn: to be angry with someone)  
10. eux  
11. leur (laisser qch à qn)
12. y (here it refers to the fact, not the people)


[^5a1]: in part, partly


## Texte

### part 1 - Olivia Ruiz

Olivia Ruiz  
_Chanteuse francaise, née à Carcassonne le 1er janvier 1980._

Dès[^2a1] l'âge de 12 ans, Olivia Ruiz monte sur scène et développe des dons[^2a2] artistiques variés: elle prend des cours de danse, monte son propre groupe de rock, les Five, et chante en duo avec son père, Didier Blanc, lui-même musicien et chanteur. 

:::{.callout-tip}
#### monter
monter sur scène - to go on stage  
monter un groupe - to form a group  
monter une entreprise - to start a business  
monter une tente - to set up a tent  
monter une machine - to assemble a machine
:::


[^2a1]: dès = à partir de, depuis
[^2a2]: le don = le talent



Après avoir obtenu un BTS de communication, la jeune femme rejoint la saison 1 de la Star Academy, qui lui permet de se faire connaître. Ses deux albums, _J'aime pas l'amour_, sorti en 2003 et _la Femme chocolat_, en 2005, sont surprenants d'originalité. Lors des Victoires de la musique 2007, elle remporte la Victoire de l'Artiste interprète féminine de l'année et la Victoire du Spectacle musicale de l'année. 

:::{.callout-tip}
#### après avoir + [participe passé] / après être + [participe passé]
avoir participe passé - a passé composé at the start of a sentence is a common construct in French, similar to English. Note, when the auxiliary verb is être and the verb is NOT reflexive, the auxiliary verb can be omitted.

- Après avoir obtenu un diplôme, il a trouvé un emploi.  
- Après être rentré / Rentré chez lui, il s'est effondré dans le canapé (effondré = collapsed, canapé = sofa).  
- Après s'être parlé, ils se sont dit au revoir. 
:::

:::{.callout-tip}
#### se faire + [infinitif]
Note the difference between:  
- faire [infinitif] à qu (to do something to someone)  
- se faire [infinitif] à qn (to make something happen or done to oneself)  

Il s'est fait couper les cheveux. (He had his hair cut.)  
Il parle à haute voix opur se faire entendre. (He speaks loudly in order to be heard.)  
Il se fait photographier. (He is having his picture taken.)  
Je me suis fait voler dans le métro. (I got robbed in the metro.)
:::

:::{.callout-tip}
#### surprenant
surprenant(e) - surprising  
surprendre - to surprise  
surpris(e) - surprised  

un événement surprenant - a surprising event

surprenant describes emotions, thus need to use subjonctif:  
Il serait surprenant que nous ne soyons pas prévenus. (It would be surprising if we were not warned.)
:::

:::{.callout-tip}
#### lors de
pendant, durant (more formal)  
Lors de son campagne électorale, il a reçu des lettres de tout le pays. 
:::


:::{.callout-tip}
#### remporter
remporter une victoire - to win a victory  
remporter une compétition - to win a competition
:::


Olivia Ruiz a réussi à créer un univers personnel et atypique où se mêlent[^3c2] rock, tango, sonorités[^3c3] latines et tziganes[^3c1] et où la guitare côtoie le piano, l'accordéon, le violon et la clarinette. Si[^3c4] la jeune chanteuse écrit elle-même certains de ses textes, les autres sont signés[^3c5] d'artistes tels que Christian Olivier (Têtes raides), Christophe Mali (Tryo), Ben Ricour, Chet, Néry ou encore Juliette.
Elle sort un troisième album, Miss Météores, en avril 2009, qu'elle coréalise[^3c6] et dont elle signe la plupart des titres.


:::{.callout-tip}
#### réussir à faire qch
to succeed in doing something  
Au bout de deux mois de recherche, on n'a toujours pas réussi à localiser l'avion disparu.
:::

:::{.callout-tip}
#### côtoyer
côtoyer qn/qch - to be next/close to  
côtoyer le lac - to be next to the lake  
côtoyer le danger - to be close to danger  
côtoyer le ridicule - to be close to the ridiculous
:::

:::{.callout-tip}
#### tels que
such as (notice it agrees with the noun it modifies, here "artistes")
:::


[^3c1]: gypsy  
[^3c2]: Note "se mêlent ... tziganes" is a reverse construction. When the subject is long, French often puts the verb before the subject. Here the subject is "rock, tango, sonorités latines et tziganes".
[^3c3]: la sonorité = the sound, eg. la sonorité d'un violon, la sonorité chantante d'italien
[^3c4]: here "si" = "although"
[^3c5]: signé = signed, here it means "written by"
[^3c6]: co-produce, co-direct


### part 2 - Thomas Dutronc

Thomas Dutronc  
_Guitariste et chanteur français, né à Paris le 15 mars 1973._

Fils unique de Jacques Dutronc et de Françoise Hardy, Thomas Dutronc s'intéresse très jeune à l'art en général et à la photographie en particulier. C'est en découvrant la musique manouche[^3d2] du guitariste belge Django Reinhardt **alors qu**'il a 18 ans que[^3d1] Thomas Dutronc **se passionne pour** la guitare. 
Il abandonne alors ses études d'arts commencées[^3d3] un an plus tôt et **apprend à en jouer**. Sa carrière musicale **commence par** une collaboration avec son père sur l'album _Brèves rencontres_ en 1994, suivie de[^3d4] l'écriture d'une chanson pour Henri Salvador. 



:::{.callout-tip}
#### alors que
while, when  
- Il a commencé à travailler alors qu'il était encore étudiant.
:::

:::{.callout-tip}
#### se passionner pour qch
to become passionate about something  
- Le président français se passionne pour le 7ème art (cinéma).
:::

:::{.callout-tip}
#### apprendre à faire qch

jouer de + [instrument]  
- jouer de la guitare  
- jouer du piano  
:::

:::{.callout-tip}
#### commencer par + [infinitif]  
- La réunion a commencé par le discours du chef.  

finir par + [infinitif]  
- Cet événement a fini par ses excuses devant tout le monde. 
:::

[^3d1]: emphasis structure: "c'est ... que"
[^3d2]: gypsy
[^3d3]: Note the past participle modifying "études", similar to English. 
[^3d4]: followed by



En 2003, il **participe à** l'élaboration[^3e1] de deux bandes originales de films[^3e2] avec son ami M (Matthieu Chedid). **Ce n'est qu'en 2007, à 34 ans, que** Thomas Dutronc sort son premier album: _Comme un manouche sans guitare_ sur lequel il écrit douze des treize textes. **Fin 2008**, il commence une tournée qui court jusqu'en avril 2009 et participe cette même année à plusieurs festivals estivaux[^3e3] dont le Fluria Sound Festival. En 2009, _Comme un manouche sans guitare_ remporte la Victoire de la chanson originale lors de la 24e cérémonie des Victoires de la musique.  


:::{.callout-tip}
#### ce n'est qu'en 2007 ... que
Again, emphasis structure: "ce ... que", except here "ce" is followed by an interesting negation. And the negation clause is of the "ne...que" structure meaning "only". 

"ce n'est qu'en 2007 ... que" = "it was not until 2007 that ..."  
:::

:::{.callout-tip}
#### participer à qch
- Il n'a pas participé au mariage de sa fille et il le regrette beaucoup.
:::

:::{.callout-tip}
#### fin + [année]
- fin 2023 - end of 2023
:::





[^3e1]: elaboration, here it means creation/production, 草拟，撰写 e.g. l'élaboration d'un project de loi = the drafting of a bill
[^3e2]: bandes originales = original soundtracks
[^3e3]: estival = summer (adj), eg. un festival estival = a summer festival



## Thème

1. After acquiring her Bachelor's degree in biology, she went to France to continue her graduate studies. 

    `après avoir`, `poursuivre`[^4a1]

    >
    Après avoir obtenu sa license de biologie, elle a poursuivi ses études supérieures en France.  
    Après avoir obtenu son diplôme en license de biologie, elle a allé en France pour poursuivre ses études supérieures.

1. Not until 2011 did he release his first album.

    `ce n'est qu'en ... que`, `jusqu'à`

    >
    Ce n'est qu'en 2011 qu'il a sorti son premier album. 


3. - Did he go to the soirée yesterday?
    - Yes, he went with her girlfriend.

    `participer à`

    >
    - Est-ce qu'il a participé à la soirée hier?
    - Oui, il y a participé avec sa copine.


4. I red many works for french writers, such as Victor Hugo, Balzac, and Proust.

    `tel que`, `comme`

    >
    J'ai lu de nombreuse œuvres d'écrivains français, **tels** que Victor Hugo, Balzac, et Proust.





[^4a1]: pursuivre = to pursue
















