---
title: "Lesson 12"
date: "2026-2-10"
categories: ["AF Nice", "B2", "Défi4", "Unit1" ]
reference-location: margin
citation-location: margin
number-sections: false
---

# Standard course

## LE TEXT

### EXTRAIT DU ROMAN "*LES FURTIFS, D'ALAIN DAMASIO*"


Alors, notre ville...? Comment s'est-elle construite? D'où sort-elle?... 

Une ville dite "libérée" est une ville soustraite[^1a1] à la gestion publique et intégralement détenue[^1a2] et gérée par une entreprise privée. Son maire est nommé par les actionnaires[^1a3], à la majorité simples des parts[^1a4]. En 2030, la ville de vos parents, qui s'applait Orange, a donc été rachetée par la multinationale du même nom, pour un prix dérisoire[^1a5]. ... 

[^1a1]: soustraitre = to remove, to take away, to subtract
[^1a2]: intégralement détenue = fully owned, entirely owned, détenir = to own, to hold
[^1a3]: actionnaires = shareholders
[^1a4]: à la majorité simple des parts = by a simple majority of shares
[^1a5]: dérisoire = derisory, ridiculously low, paltry, negligible

Je vous rappelle que Paris, racheté par LVMH, ou Cannes, racheté par la Warner, ont vendu leur nom à des prix astronomiques. ...


Alors, Orange a commencé par faire ce qu'ils font dans toutes les villes "libérées". Ils ont mis en place leurs trois forfaits[^2a1] citoyens: un forfait priviège pour les citoyens aisés[^2a2] et leur famille, un forfait premium pour les classes moyennes, et un forfait standard pour les plus démunis[^2a3]. Et à ceux qui ne pouvaient pas payer le forfait standard, ils ont proposé de partir. D'abord gentiment, avec une prime de départ[^2a4], puis un peu moins courtoisement avec des lettres et des huissiers[^2a7], puis encore moins courtoisement[^2a5] avec les retrait[^2a6] des aides sociales et l'interdiction de l'école aux enfants. Ça a suffis neuf fois sur dix. Mais les dix pour cent restant n'ont pas voulu céder et ils se sont battus[^2a8] jusqu'au bout[^2a9]. Afin de[^2a10] garder[^2a11] leur logement et de rester citoyens de la ville. ...

[^2a1]: forfait = package, plan, subscription
[^2a2]: aisé = wealthy, affluent
[^2a3]: démunis = destitute, deprived, underprivileged
[^2a4]: prime de départ = severance pay, departure bonus, prime = bonus, allowance
[^2a5]: courtoisement = courteously, politely, with courtesy
[^2a6]: retrait = withdrawal, removal
[^2a7]: huissier = bailiff, court officer
[^2a8]: se battre = to fight, to struggle
[^2a9]: jusqu'au bout = until the end, to the end
[^2a10]: afin de = in order to
[^2a11]: garder = to keep, to retain


Orange a commencé par déstruire des cités et des tours[^3a1], pour "redynamiser le centre urbain", en expulsant[^3a2] les habitants et en les relogeant[^3a3] hors de la ville, dans les hôtels-péniches[^3a4] que vous connaissez, sur le Rhône. Toutefois[^3a5] une tour a tenu bon[^3a6]. On l'a vite rebaptisée[^3a7] la Tour-Rouge à cause des fumigènes[^3a8] qui brûlaient toutes les nuits sur le toit[^3a9], pour flouer[^3a10] les drones. Orange a choisi la voie jurisdique dure et a décidé d'en faire le siège, pendant plus de cent jours. Après un mois, les habitants de la tour ont commencé crever[^3a11] de faim, ils étaient heureusement ravitaillés[^3a12] par les caves, par les toits, des drones pirates les livraient[^3a13] sur les balcons...

[^3a1]: cité = housing estate, tower block, cité = city, town; tour = tower, here refers to high rise buildings for housing
[^3a2]: expulser = to evict, to expel, to remove
[^3a3]: reloger = to rehouse, to relocate
[^3a4]: hôtel-péniche = hotel barge, a hotel on a boat, péniche = barge
[^3a5]: toutefois = however, nevertheless, nonetheless
[^3a6]: tenir bon = to hold out, to hold firm, to stand firm, tenir = to hold, to keep
[^3a7]: rabaptiser qch = to rename sth
[^3a8]: fumigène = smoke bomb
[^3a9]: toit = roof, top
[^3a10]: flouer = to deceive, to trick, to fool
[^3a11]: crever de faim = to starve, to die of hunger, crever = to burst, to die
[^3a12]: ravitailler = to supply, to provide, to resupply
[^3a13]: livrer = to deliver, to supply

Mais tous ceux qui essayaient de sortir étaient aussitôt[^4a1] capturés par les milices[^4a2] et incarcérés[^4a3] pour violation du droit de propriété. La résistance était âpre[^4a4] parce que c'était le statut même de la ville qui se jouait[^4a5] là-bas. Tout le monde le sentait. Si la Tour-Rouge tombait, les gens savaient que cette ville cesserait de fonctionner comme une démocratie. 

[^4a1]: aussitôt = immediately, as soon as
[^4a2]: milice = militia
[^4a3]: incarcérer = to incarcerate
[^4a4]: âpre = rough, tough, fierce, harsh
[^4a5]: se jouer = to be at stake


## Activité 1 : Mise en route

Qu’est-ce qu’un roman ?   

- C’est une histoire écrite qui a été publiée.   
- Histoire d’amour - fiction - aventure - science fiction   
- Lire pour le plaisir   

Quel(s) roman(s) français connaissez-vous ?   

- Albert Camus : L’étranger - La peste  
- Antoine de St Exupéry : Le petit prince  
- Alexandre Dumas : Le comte de Monte-Cristo - Les trois mousquetaires  
- Jean-Paul Sartre  
- Guy de Maupassant   
- Victor Hugo   
- Molière   
- Simone de Beauvoir   


## Activité 2 : Compréhension écrite

**Livre de l’élève p.25**

Première lecture  
Lisez l’extrait du roman Les furtifs d’Alain Damasio. Que raconte le narrateur ?   

Pour vous aider :   

- Les caractéristiques du fonctionnement de la ville :   
- Quelle est la comparaison ?   
- Quelle est la critique ?   


<br>

- C’est l’histoire d’une ville qui a été vendue / privatisée. L’entreprise à fait 3 classes sociales. Les gens qui ne pouvaient pas payer pour avoir accès à ce service, n’avaient pas d’endroits où vivre. Ils se révoltent.   
- Les gens qui se révoltent n’ont pas réussi de lutter contre les entreprises / la situation.   
- → Privatisation des services publics / augmentation des loyers / surveillance publique   
  
À votre avis, pourquoi les expressions villes “libérées” et “redynamiser le centre urbain” sont-elles entre guillemets[^6a1] ?   

- Pour convaincre le public   
- Ironie   
- Pour mettre de la distance avec l’idée.   


[^6a1]: guillemet = quotation mark, inverted commas, quote marks




## Activité 3 : Grammaire  

**_Livre de l’élève p.27_**  

### Étape 1 : Réflexion  

**Lisez ces phrases extraites du roman d’Alain Damasio.**

> C’était le statut même de la ville qui se jouait. Tout le monde le sentait. 

Que remplace le pronom le ?   

- Le pronom remplace la proposition.   

**Réécrivez la phrase sans le pronom.** 

> Tout le monde sentait que c’était le statut même de la ville qui se jouait.   

### Étape 2 : La règle   

**Le pronom neutre le peut remplacer : **

- Un adjectif
  - Exemple  : _C’est une ville magnifique et elle le sera toujours._


- Une proposition / une phrase ou une idée
  - Exemple : _C’était le statut même de la ville qui se jouait. Tout le monde le sentait._


### Étape 3 : Exercices 


**Cahier d’activité p.10**  
**Réécrivez les phrases suivantes en remplaçant ce qui est en gras par le pronom le.**
  
Je lui ai répété plusieurs fois d’être plus économe mais rien ne change.   
→   
Il est sublime, sans aucun doute !   
→   
Nous souhaitons que ça change et nous ferons tout pour avoir ce changement.   
→   
Vous dites que vous vous excusez mais vous ne pensez pas vos excuses.   
→   
Elle va annoncer le nouveau projet qu’elle a pour la ville la semaine prochaine.   
→   
  
**À deux, imaginez ce que remplace le pronom neutre le dans les phrases suivantes : **

- Les villes le sont de plus en plus.   
- Chères   
- Les citadins le sont de moins en moins.   
- Les entreprises du numérique le veulent.   
- Les élus l’oublient quelquefois.  
- Les élus oublient quelquefois la qualité de vie dans la banlieue.   
- La professeure le dit souvent.   
- Attends   
  

### Vocabulaire  

- Un fumigène (n.m)  
- Un forfait (n.m)  
- Tenir bon (exp.) = résister (v.)   
- Un huissier (n.m)  
- Dérisoire (adj.)   
- Un guillemet (n.m)  
  
  
------------  

## Devoirs

:::{.callout-warning}
##### Devoirs
Pour le mercredi 11 février  

Revoir la leçon de grammaire sur le pronom neutre `le`.   
:::

###  Faire l’exercice suivant : 

#### Exercice : Modifiez la réponse en utilisant le pronom `le` pour éviter la répétition.  

**Exemple:**  

- Est-ce que ma commande est prête, s'il vous plaît?  
- Attendez... Non, elle n'est pas encore prête, elle sera prête dans une heure.  

> → Attendez... Non, elle ne l’est pas encore, elle le sera dans une heure.  

**a).**   

- Lucas Pouille n'est pas le meilleur joueur français!  
- Non, mais il sera bientôt le meilleur joueur français, j'en suis certain.  

> → Non, mais il `le` sera bientôt, j'en suis certain.

**b).**

- Le studio, il est en bon état[^7a3]?  
- Oui, il est en bon état: il a été refait l'année dernière.  

> → Oui, il `l`'est: il a été refait l'année dernière.

**c).**  

- Est-ce que Julie a invité Alice à son mariage?  
- Je ne crois pas qu'elle ait invité Alice à son mariage.  

> →  Je ne `le` crois pas.

**d).**  

- Tu as contacté Pasquier pour la réparation?  
- Non! Personne ne m'a demandé de contacter Pasquier pour la réparation!  

> →  Non! personne ne me `l`'a demandé.


**e).**   

- Tu n'es plus fâchée[^7a1] avec Lorène?  
- Moi, fâchée ? Mais je n'ai jamais été fâchée!  

> →  Moi, fâchée? Mais je ne `l`'ai jamais été!

**f).**  

- Bon, puisque[^7a2] c'est comme ça, je pars!  
- Mais non, je t'interdis de partir!  

> →  Mais non, je `le` interdis!

[^7a1]: angry, upset, mad
[^7a2]: since, as, because
[^7a3]: condition, state


