---
title: "Lesson 15"
date: "2026-2-13"
categories: ["AF Nice", "B2", "Défi4", "Unit1", "cause", "conséquence", "grammaire"]
reference-location: margin
citation-location: margin
number-sections: false
---

# Standard course


## EXPRESSION DE LA CAUSE

### LES CONJONCTIONS


- ["parce que"]{.mark}, ["comme"]{.mark}, ["puisque"]{.mark} sont les conjonctions les plus courantes.  

  - ["Parce que"]{.mark} répond à la question _"Pourquoi?"_   
    La cause est considérée comme banale[^1a1]. ["parce que"]{.mark} n'est pas, en général, en tête de phase:  
      - _Exemple:  Il est allé voir le médecin [parce qu]{.mark}'il a de la fièvre[^1a2] depuis plusieurs jours._   
<br><br>

  - ["Comme"]{.mark} se place en tête de la phrase et met la cause en valeur:  
    - _Exemple: [Comme]{.mark} il n'a pas plu depuis un mois, on est obligé d'arroser le jardin tous les jours._  
<br><br>

  - ["Puisque"]{.mark} introduit une cause évidente pour celui qui parle et en général connue de l'interlocuteur[^1a3]  
    - _Exemple: [Puisqu]{.mark}'il fait beau, déjeunons sur la terrasse._  
    - _Exemple: Tu devrais aller voir cette exposition, [puisque]{.mark} tu aimes Picasso._  
<br><br>


- ["étant donné que"]{.mark}, ["du fait que"]{.mark} introduisent une cause connue de tous. Ces locutions[^1a4] se placent en tête de phrase ou après la conséquence.  

  - "[Étant donné que]{.mark}" s'emploie surtout à l'écrit: 
    - _Exemple: [Étant donné qu]{.mark}'il a dix-huit ans, il peut passer le permis de conduire._  
    - _Exemple: Les enfants ont dû rester à la maison [étant donné que]{.mark} les professeurs des écoles étaient en grève._  
<br><br>

  - "[Du fait que]{.mark}" est employé à l'oral et à l'écrit:  
    - _Exemple: [Du fait que]{.mark} toute le monde était fatiqué, nous avons arrêté la réunion._  
    - _Exemple: Le ministre a laissé ses fonctions [du fait qu]{.mark}'il était très malade._
<br><br>

  - ["sous prétexte que"]{.mark} introduit une cause fausse:  
    - _Exemple: Il n'est pas venu [sous prétexte qu]{.mark}'il était malade. (mais je ne le crois pas)_  


[^1a1]: courante, évidente, normale, habituelle
[^1a2]: fever
[^1a3]: person you are talking to
[^1a4]: expressions formed by several words


### LES PREPOSITIONS

- ["grâce à"]{.mark} introduit une cause dont la conséquence est positive. Il est suivi d'un nom ou d'un pronom.
Quand il y a deux causes, la seconde cause est introduite par ["à"]{.mark}:
  - _Exemple: Elle a trouvé un appartement [grâce à]{.mark} des amis qui travaillent dans une agence._  
  - _Exemple: Il a pu réussir [grâce à]{.mark} elle et [à]{.mark} quelques amis._  
<br><br>

- ["à cause de"]{.mark} introduit en général une cause dont la conséquence est négative; il est suivi d'un nom ou d'un pronom. Quand il y a deux causes, la seconde est introduite par ["de"]{.mark}.  
  - _Exemple: Le match n'a pas eu lieu [à cause du]{.mark} mauvais temps._
  - _Exemple: On est arrivés en retard au théâtre [à cause de]{.mark} lui et [des]{.mark} embouteillages._  
<br><br>

- ["en raison de"]{.mark} introduit une cause dont la conséquence est neutre; il est suivi d'un nom; il est employé surtout à l'écrit:  
  - _Exemple: _Le magasin sera fermé [en raison des]{.mark} fêtes de Pâques._  
<br><br>


- ["étant donné de"]{.mark} et ["du fait de"]{.mark} introduisent une cause connue de tous; ils sont suivis d'un nom:  
  - _Exemple: [Étant donné]{.mark} la pollution dans les grandes villes, les gens préfèrent aller vivre en province._  
  - _Exemple: Ils sont allés vivre en banlieue [du fait de]{.mark} l'augmentation des loyers en ville._  



### LES MOTS DE LIAISON

- ["car"]{.mark} est employé plutôt à l'écrit; il introduit une explication à ce qui vient d'être dit:  
  - _Exemple: Ils avaient passé l'après-midi à bavarder[^2a1] au coin du feu [car]{.mark} dehors il faisait très froid._  
<br><br>

- ["en effet"]{.mark} est employé à l'oral et à l'écrit; il introduit une explication à ce qui vient d'être dit:  
  - _Exemple: Ils commencèrent à se dépêcher[^2a2]; [en effet]{.mark} le ciel s'assombrissait[^2a3] et annonçait un orage._
  - _Exemple: Tu es pressé? - [En effet]{.mark}, je suis en retard; j'ai un rendez-vous._   



[^2a1]: bavarder = gossip, chat
[^2a2]: se dépêcher = hurry up
[^2a3]: s'assombrir = darken


## EXPRESSION DE LA CONSEQUENCE


### LES CONJUNCTIONS

- ["si bien que"]{.mark} n'a pas de nuance particulière; il peut être renforcé par ["tant et si bien que"]{.mark}  
  - _Exemple: Il ment beaucoup [si bien que]{.mark} personne ne croit ce qu'il dit._  
  - _Exemple: Il s'est opposé au gouvernement [tant et si bien qu]{.mark}'il a dû démissionner._  
<br><br>

- ["de sorte que"]{.mark} est une  nuance de ["si bien que"]{.mark} et introduit une conséquence certaine.  
  - _Exemple: Il conduisait sans permis [de sorte qu]{.mark}'il a été condamné à la prison. _  
<br><br>

- ["si"]{.mark}, ["tellement"]{.mark}, ["tant"]{.mark} + [que]{.mark} expriment l'intensité.  

- ["si"]{.mark} donne un caractère intensif à l'adjectif et à l'adverbe. Il est aussi employé avec certaines expressions comme avoir faim, soif, peur, envie, etc.:  
  - _Exemple: Elle était [si]{.mark} généreuse [que]{.mark} tout le monde l'aimait._  
  - _Exemple: Il conduit [si]{.mark} vit [que]{.mark} personne ne veut monter dans sa voiture._  
  - _Exemple: J'étais [si]{.mark} en colère [que]{.mark} je suis parti sans dire au revoir._  
<br><br>

- ["tant"]{.mark} donne un caractère quantitatif au verbe, ["tant de"]{.mark} au nom:  
  - _Exemple: Il pleut [tant que]{.mark} les champs sont inondés._  
  - _Exemple: Ils ont fait [tant de]{.mark} bruit [que]{.mark} les voisins se sont plaints[^3a1]._
<br><br>

- ["tellement"]{.mark} donne un caractère intensif et quantitatif à l'adjectif, à l'adverbe et au verbe; ["tellement de"]{.mark} au nom.  
  - _Exemple: Ce chien est [tellement]{.mark} agressif [qu]{.mark}'il aboie[^3a2] sans arrêt._  
  - _Exemple: Ils habitent [tellement de]{.mark} loin [que]{.mark} nous ne les voyons pas souvent._  
  - _Exemple: On a [tellement]{.mark} ri[^3a3] [qu]{.mark}'on n'a pas vu qu'il était très tard._  
  - _Exemple: J'ai [tellement de]{.mark} travail [que]{.mark} je ne prendrai pas de vacances._  



[^3a1]: se plaindre = complain
[^3a2]: aboyer = bark
[^3a3]: rire = laugh






